******Car-Dheko_Used_Car_Price_Prediction******

There are 6 files of cities data

****Data Processing****

**a)	Import and concatenate:**

i)	Import all city’s dataset which is in unstructured format.

ii)	Convert it into a  structured format.

iii)Added a new column named ‘City’ and assign values for all rows with the name of the respective city.

iv)	Concatenate all datasets and make it as a single dataset.

**Banglore**

Perfectly Done unstructured to structured Banglore cars

In [30]:
import os
import pandas as pd
import ast
from collections import defaultdict

input_folder = "csv_files"
output_file = os.path.join(input_folder, "structured_cars_data.csv")

city_map = {
    "bangalore_cars.csv": "BANGALORE",
    "chennai_cars.csv": "CHENNAI",
    "delhi_cars.csv": "DELHI",
    "hyderabad_cars.csv": "HYDERABAD",
    "jaipur_cars.csv": "JAIPUR",
    "kolkata_cars.csv": "KOLKATA"
}

def parse_dict_column(column):
    return column.apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.strip().startswith("{") else x)

def flatten_overview(overview_data):
    if isinstance(overview_data, dict):
        return {item['key']: item['value'] for item in overview_data.get("top", []) if isinstance(item, dict)}
    return {}

def flatten_feature(data):
    features = []
    if isinstance(data, dict):
        top = data.get("top", [])
        features.extend(f.get("value") for f in top if isinstance(f, dict))
        for section in data.get("data", []):
            if isinstance(section, dict):
                for item in section.get("list", []):
                    if isinstance(item, dict):
                        val = item.get("value")
                        if val:
                            features.append(val)
    return {'Feature_' + str(i): v for i, v in enumerate(features)}

def flatten_specs(data):
    specs = {}
    if isinstance(data, dict):
        for item in data.get("top", []):
            if isinstance(item, dict):
                k = item.get("key")
                v = item.get("value")
                if k and v:
                    specs[k] = v
        for section in data.get("data", []):
            if isinstance(section, dict):
                for item in section.get("list", []):
                    if isinstance(item, dict):
                        k = item.get("key")
                        v = item.get("value")
                        if k and v:
                            specs[k] = v
    return specs

def deduplicate_columns(columns):
    seen = defaultdict(int)
    new_columns = []
    for col in columns:
        if seen[col] == 0:
            new_columns.append(col)
        else:
            new_columns.append(f"{col}.{seen[col]}")
        seen[col] += 1
    return new_columns

dfs_combined = []

for file_name in os.listdir(input_folder):
    if file_name in city_map:
        file_path = os.path.join(input_folder, file_name)
        print(f"📥 Processing: {file_path}")
        
        try:
            df = pd.read_csv(file_path)

            for col in ["new_car_detail", "new_car_overview", "new_car_feature", "new_car_specs"]:
                if col in df.columns:
                    df[col] = parse_dict_column(df[col])

            df_overview = pd.DataFrame(df["new_car_overview"].apply(flatten_overview).tolist()) if "new_car_overview" in df.columns else pd.DataFrame()
            df_detail = pd.json_normalize(df["new_car_detail"]) if "new_car_detail" in df.columns else pd.DataFrame()
            df_feature = pd.DataFrame(df["new_car_feature"].apply(flatten_feature).tolist()) if "new_car_feature" in df.columns else pd.DataFrame()
            df_specs = pd.DataFrame(df["new_car_specs"].apply(flatten_specs).tolist()) if "new_car_specs" in df.columns else pd.DataFrame()
            base_cols = df[["car_links"]] if "car_links" in df.columns else pd.DataFrame()

            df_final = pd.concat([base_cols, df_detail, df_overview, df_feature, df_specs], axis=1)
            df_final.columns = deduplicate_columns(df_final.columns)

            df_final["City"] = city_map[file_name]
            dfs_combined.append(df_final)

        except Exception as e:
            print(f"❌ Error processing {file_name}: {e}")

# Save final output
if dfs_combined:
    final_df = pd.concat(dfs_combined, ignore_index=True)
    final_df.to_csv(output_file, index=False)
    print(f"✅ Final structured data saved to: {output_file}")
else:
    print("⚠️ No data was processed.")

📥 Processing: csv_files\bangalore_cars.csv
📥 Processing: csv_files\chennai_cars.csv
📥 Processing: csv_files\delhi_cars.csv
📥 Processing: csv_files\hyderabad_cars.csv
📥 Processing: csv_files\jaipur_cars.csv
📥 Processing: csv_files\kolkata_cars.csv
✅ Final structured data saved to: csv_files\structured_cars_data.csv

In [7]:
import pandas as pd

file_name=r"C:\Users\USER\Desktop\Car-Dheko_Used_Car_Price_Prediction\csv_files\structured_cars_data.csv"

# Read the CSV file into a Pandas DataFrame
df_check = pd.read_csv(file_name)

nan_summary = pd.DataFrame({
    'Column': df_check.columns,
    'Data Type': df_check.dtypes,
    'Non-Null Count': df_check.notna().sum(),
    'NaN Count': df_check.isna().sum(),
    'NaN Percentage': (df_check.isna().mean() * 100).round(2)
}).reset_index(drop=True)

# Display ALL rows without truncation
with pd.option_context('display.max_rows', None, 'display.width', 1000):
    print(nan_summary)

C:\Users\USER\AppData\Local\Temp\ipykernel_23328\1927730870.py:6: DtypeWarning: Columns (14,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,208,209,210,211,212,213,214,215,216,217,218) have mixed types. Specify dtype option on import or set low_memory=False.
  df_check = pd.read_csv(file_name)

                       Column Data Type  Non-Null Count  NaN Count  NaN Percentage
0                   car_links    object            8369          0            0.00
1                          it     int64            8369          0            0.00
2                          ft    object            8369          0            0.00
3                          bt    object            8365          4            0.05
4                          km    object            8369          0            0.00
5                transmission    object            8369          0            0.00
6                     ownerNo     int64            8369          0            0.00
7                       owner    object            8369          0            0.00
8                         oem    object            8369          0            0.00
9                       model    object            8369          0            0.00
10                  modelYear     int64            8369          0            0.00
11           centralVariantId     int64            8369          0            0.00
12                variantName    object            8369          0            0.00
13                      price    object            8369          0            0.00
14                priceActual    object            1670       6699           80.05
15                priceSaving   float64               0       8369          100.00
16             priceFixedText   float64               0       8369          100.00
17        trendingText.imgUrl    object            8369          0            0.00
18       trendingText.heading    object            8369          0            0.00
19          trendingText.desc    object            8369          0            0.00
20          Registration Year    object            8317         52            0.62
21         Insurance Validity    object            8365          4            0.05
22                  Fuel Type    object            8369          0            0.00
23                      Seats    object            8363          6            0.07
24                 Kms Driven    object            8367          2            0.02
25                        RTO    object            7475        894           10.68
26                  Ownership    object            8337         32            0.38
27        Engine Displacement    object            8365          4            0.05
28               Transmission    object            8369          0            0.00
29        Year of Manufacture   float64            8349         20            0.24
30                  Feature_0    object            8304         65            0.78
31                  Feature_1    object            8304         65            0.78
32                  Feature_2    object            8304         65            0.78
33                  Feature_3    object            8304         65            0.78
34                  Feature_4    object            8302         67            0.80
35                  Feature_5    object            8301         68            0.81
36                  Feature_6    object            8300         69            0.82
37                  Feature_7    object            8300         69            0.82
38                  Feature_8    object            8300         69            0.82
39                  Feature_9    object            8299         70            0.84
40                 Feature_10    object            8298         71            0.85
41                 Feature_11    object            8296         73            0.87
42                 Feature_12    object            8293         76            0.91
43                 Feature_13    object            8293         76            0.91
44                 Feature_14    object            8292         77            0.92
45                 Feature_15    object            8289         80            0.96
46                 Feature_16    object            8289         80            0.96
47                 Feature_17    object            8282         87            1.04
48                 Feature_18    object            8281         88            1.05
49                 Feature_19    object            8271         98            1.17
50                 Feature_20    object            8267        102            1.22
51                 Feature_21    object            8262        107            1.28
52                 Feature_22    object            8253        116            1.39
53                 Feature_23    object            8245        124            1.48
54                 Feature_24    object            8245        124            1.48
55                 Feature_25    object            8240        129            1.54
56                 Feature_26    object            8223        146            1.74
57                 Feature_27    object            8217        152            1.82
58                 Feature_28    object            8174        195            2.33
59                 Feature_29    object            8162        207            2.47
60                 Feature_30    object            8158        211            2.52
61                 Feature_31    object            8138        231            2.76
62                 Feature_32    object            8104        265            3.17
63                 Feature_33    object            8052        317            3.79
64                 Feature_34    object            8040        329            3.93
65                 Feature_35    object            7997        372            4.44
66                 Feature_36    object            7900        469            5.60
67                 Feature_37    object            7856        513            6.13
68                 Feature_38    object            7771        598            7.15
69                 Feature_39    object            7766        603            7.21
70                 Feature_40    object            7740        629            7.52
71                 Feature_41    object            7724        645            7.71
72                 Feature_42    object            7662        707            8.45
73                 Feature_43    object            7624        745            8.90
74                 Feature_44    object            7592        777            9.28
75                 Feature_45    object            7505        864           10.32
76                 Feature_46    object            7421        948           11.33
77                 Feature_47    object            7382        987           11.79
78                 Feature_48    object            7324       1045           12.49
79                 Feature_49    object            7209       1160           13.86
80                 Feature_50    object            7102       1267           15.14
81                 Feature_51    object            7022       1347           16.10
82                 Feature_52    object            6957       1412           16.87
83                 Feature_53    object            6871       1498           17.90
84                 Feature_54    object            6794       1575           18.82
85                 Feature_55    object            6732       1637           19.56
86                 Feature_56    object            6656       1713           20.47
87                 Feature_57    object            6570       1799           21.50
88                 Feature_58    object            6490       1879           22.45
89                 Feature_59    object            6450       1919           22.93
90                 Feature_60    object            6349       2020           24.14
91                 Feature_61    object            6194       2175           25.99
92                 Feature_62    object            6156       2213           26.44
93                 Feature_63    object            6060       2309           27.59
94                 Feature_64    object            5938       2431           29.05
95                 Feature_65    object            5777       2592           30.97
96                 Feature_66    object            5503       2866           34.25
97                 Feature_67    object            5386       2983           35.64
98                 Feature_68    object            5262       3107           37.13
99                 Feature_69    object            5138       3231           38.61
100                Feature_70    object            5011       3358           40.12
101                Feature_71    object            4792       3577           42.74
102                Feature_72    object            4727       3642           43.52
103                Feature_73    object            4586       3783           45.20
104                Feature_74    object            4348       4021           48.05
105                Feature_75    object            4158       4211           50.32
106                Feature_76    object            4030       4339           51.85
107                Feature_77    object            3869       4500           53.77
108                Feature_78    object            3713       4656           55.63
109                Feature_79    object            3619       4750           56.76
110                Feature_80    object            3415       4954           59.19
111                Feature_81    object            3273       5096           60.89
112                Feature_82    object            3045       5324           63.62
113                Feature_83    object            2960       5409           64.63
114                Feature_84    object            2823       5546           66.27
115                Feature_85    object            2645       5724           68.40
116                Feature_86    object            2488       5881           70.27
117                Feature_87    object            2375       5994           71.62
118                Feature_88    object            2281       6088           72.74
119                Feature_89    object            2124       6245           74.62
120                Feature_90    object            2033       6336           75.71
121                Feature_91    object            1940       6429           76.82
122                Feature_92    object            1852       6517           77.87
123                Feature_93    object            1675       6694           79.99
124                Feature_94    object            1587       6782           81.04
125                Feature_95    object            1479       6890           82.33
126                Feature_96    object            1366       7003           83.68
127                Feature_97    object            1226       7143           85.35
128                Feature_98    object            1139       7230           86.39
129                Feature_99    object            1055       7314           87.39
130               Feature_100    object            1001       7368           88.04
131               Feature_101    object             932       7437           88.86
132               Feature_102    object             866       7503           89.65
133               Feature_103    object             815       7554           90.26
134               Feature_104    object             775       7594           90.74
135               Feature_105    object             711       7658           91.50
136               Feature_106    object             659       7710           92.13
137               Feature_107    object             628       7741           92.50
138               Feature_108    object             564       7805           93.26
139               Feature_109    object             534       7835           93.62
140               Feature_110    object             501       7868           94.01
141               Feature_111    object             449       7920           94.63
142               Feature_112    object             395       7974           95.28
143               Feature_113    object             362       8007           95.67
144               Feature_114    object             324       8045           96.13
145               Feature_115    object             271       8098           96.76
146               Feature_116    object             246       8123           97.06
147               Feature_117    object             231       8138           97.24
148               Feature_118    object             211       8158           97.48
149               Feature_119    object             175       8194           97.91
150               Feature_120    object             154       8215           98.16
151               Feature_121    object             128       8241           98.47
152               Feature_122    object             112       8257           98.66
153               Feature_123    object              95       8274           98.86
154               Feature_124    object              67       8302           99.20
155               Feature_125    object              50       8319           99.40
156               Feature_126    object              45       8324           99.46
157               Feature_127    object              41       8328           99.51
158               Feature_128    object              36       8333           99.57
159               Feature_129    object              30       8339           99.64
160               Feature_130    object              27       8342           99.68
161               Feature_131    object              22       8347           99.74
162               Feature_132    object              21       8348           99.75
163               Feature_133    object              19       8350           99.77
164               Feature_134    object              16       8353           99.81
165               Feature_135    object              16       8353           99.81
166               Feature_136    object              15       8354           99.82
167                   Mileage    object            8082        287            3.43
168                    Engine    object            8365          4            0.05
169                 Max Power    object            8309         60            0.72
170                    Torque    object            8309         60            0.72
171                   Seats.1   float64            8363          6            0.07
172                     Color    object            8366          3            0.04
173               Engine Type    object            8074        295            3.52
174              Displacement   float64            8365          4            0.05
175                Max Torque    object            8309         60            0.72
176            No of Cylinder   float64            8338         31            0.37
177       Values per Cylinder   float64            8318         51            0.61
178       Value Configuration    object            6153       2216           26.48
179         Fuel Suppy System    object            6642       1727           20.64
180              BoreX Stroke    object            2405       5964           71.26
181         Compression Ratio    object            1895       6474           77.36
182             Turbo Charger    object            7329       1040           12.43
183             Super Charger    object            6407       1962           23.44
184                    Length    object            8290         79            0.94
185                     Width    object            8286         83            0.99
186                    Height    object            8290         79            0.94
187                Wheel Base    object            8206        163            1.95
188               Front Tread    object            4811       3558           42.51
189                Rear Tread    object            4799       3570           42.66
190               Kerb Weight    object            8310         59            0.70
191              Gross Weight    object            3828       4541           54.26
192                  Gear Box    object            8263        106            1.27
193                Drive Type    object            6809       1560           18.64
194          Seating Capacity   float64            8363          6            0.07
195             Steering Type    object            8114        255            3.05
196            Turning Radius    object            6769       1600           19.12
197          Front Brake Type    object            8273         96            1.15
198           Rear Brake Type    object            8273         96            1.15
199                 Top Speed    object            4607       3762           44.95
200              Acceleration    object            4857       3512           41.96
201                 Tyre Type    object            8292         77            0.92
202           No Door Numbers   float64            8358         11            0.13
203              Cargo Volumn    object            6776       1593           19.03
204                Wheel Size    object            5386       2983           35.64
205          Alloy Wheel Size    object            5386       2983           35.64
206  Ground Clearance Unladen    object             515       7854           93.85
207                      City    object            8369          0            0.00
208               Feature_137    object              10       8359           99.88
209               Feature_138    object               8       8361           99.90
210               Feature_139    object               5       8364           99.94
211               Feature_140    object               5       8364           99.94
212               Feature_141    object               5       8364           99.94
213               Feature_142    object               4       8365           99.95
214               Feature_143    object               4       8365           99.95
215               Feature_144    object               4       8365           99.95
216               Feature_145    object               3       8366           99.96
217               Feature_146    object               3       8366           99.96
218               Feature_147    object               1       8368           99.99

In [11]:
df_check[['price','bt', 'Kms Driven','owner','Year of Manufacture','Mileage','Fuel Type','Registration Year','modelYear', 'Insurance Validity','Gear Box', 'modelYear', 'Transmission', 'Seats', 'City', 'Engine Displacement']].tail(10)

,price,bt,Kms Driven,owner,Year of Manufacture,Mileage,Fuel Type,Registration Year,modelYear,Insurance Validity,Gear Box,modelYear,Transmission,Seats,City,Engine Displacement
8359,₹ 2.50 Lakh,Sedan,"60,000 Kms",1st Owner,2010.0,17.5 kmpl,Petrol,2010,2010,Third Party insurance,5 Speed,2010,Manual,5 Seats,KOLKATA,1298 cc
8360,₹ 1 Lakh,Hatchback,"30,000 Kms",3rd Owner,2002.0,16.1 kmpl,Petrol,2002,2002,Third Party insurance,4 Speed,2002,Manual,4 Seats,KOLKATA,796 cc
8361,₹ 4 Lakh,Sedan,"60,000 Kms",1st Owner,2013.0,16.8 kmpl,Petrol,2013,2013,Third Party insurance,5 Speed,2013,Manual,5 Seats,KOLKATA,1497 cc
8362,₹ 3.60 Lakh,Hatchback,"70,000 Kms",1st Owner,2015.0,16.2 kmpl,Petrol,2015,2015,Third Party insurance,5 Speed,2015,Manual,5 Seats,KOLKATA,1199 cc
8363,₹ 1.50 Lakh,Hatchback,"30,000 Kms",1st Owner,2009.0,NaN,Petrol,2009,2009,Third Party insurance,5 Speed,2009,Manual,5 Seats,KOLKATA,1086 cc
8364,₹ 5.10 Lakh,Hatchback,"10,000 Kms",1st Owner,2022.0,25.24 kmpl,Petrol,2022,2022,Third Party insurance,5-Speed,2022,Manual,5 Seats,KOLKATA,998 cc
8365,₹ 1.80 Lakh,Hatchback,"1,20,000 Kms",1st Owner,2014.0,22.74 kmpl,Petrol,2014,2014,Third Party insurance,5 Speed,2014,Manual,5 Seats,KOLKATA,796 cc
8366,₹ 5.50 Lakh,Sedan,"50,000 Kms",3rd Owner,2011.0,11.74 kmpl,Petrol,2011,2011,Third Party insurance,7 Speed,2011,Automatic,5 Seats,KOLKATA,1796 cc
8367,₹ 1.40 Lakh,Hatchback,"40,000 Kms",1st Owner,2012.0,18.5 kmpl,Petrol,2012,2012,Third Party insurance,5 Speed,2012,Manual,5 Seats,KOLKATA,1197 cc
8368,₹ 5 Lakh,SUV,"1,20,000 Kms",2nd Owner,2017.0,19.72 kmpl,Diesel,2017,2017,Third Party insurance,6 Speed,2017,Manual,5 Seats,KOLKATA,1461 cc

✅ Selected Features and Justifications

| Column               | Description                                   | Justification                                                                 |
|----------------------|-----------------------------------------------|-------------------------------------------------------------------------------|
| `price`              | Selling price of the used car (Target variable) | This is the variable we're predicting.                                        |
| `bt`                 | Possibly body type or build type              | Vehicle type (e.g., SUV, sedan) affects demand, pricing, and buyer preference.|
| `Kms Driven`         | Total kilometers driven                        | Indicates vehicle usage; higher values usually reduce resale value.           |
| `owner`              | Number or type of previous owners              | Helps assess usage history and trust; fewer owners often mean better value.   |
| `Year of Manufacture`| Production year of the car                     | Indicates age; newer cars typically sell for higher prices.                   |
| `Mileage`            | Fuel efficiency (e.g., km/l)                   | Higher mileage is appealing and adds value to the car.                        |
|                         |
| `Fuel Type`          | Petrol, Diesel, CNG, Electric, etc.            | Different fuels affect running costs and buyer demand.                        |
| `Registration Year`  | Year the car was registered                    | Might differ from manufacturing year; important for insurance and resale.     |
| `modelYear`          | Year of manufacture                            | Reflects the age of the vehicle; newer cars tend to sell for higher prices.   |
| `Insurance Validity` | Remaining insurance period                     | A valid insurance policy adds value and trust for the buyer.                  |
| `Gear Box`           | Number of gears                                | Indicates car performance and class; more gears can mean better performance.  |
| `Transmission`       | Manual or Automatic                            | Automatics generally command a higher resale price, especially in cities.     |
| `Seats`              | Number of seats                                | More seating capacity appeals to families and commercial buyers.              |
| `City`               | City where the car is listed                   | Price trends vary by location due to demand, taxes, and road conditions.      |
| `Engine Displacement`| Engine size in CC                              | Affects performance, tax class, and buyer interest.                           |

In [12]:
df_check['Engine Displacement'].unique()

array(['998 cc', '1497 cc', '1199 cc', '1197 cc', '1248 cc', '1956 cc',
       '1198 cc', '1462 cc', '2179 cc', '1950 cc', '1396 cc', '1995 cc',
       '1498 cc', '4663 cc', '1086 cc', '1991 cc', '1968 cc', '1998 cc',
       '2982 cc', '1461 cc', '1797 cc', '796 cc', '1353 cc', '2925 cc',
       '2987 cc', '2967 cc', '999 cc', '1341 cc', '1496 cc', '1582 cc',
       '1798 cc', '1120 cc', '1969 cc', '1451 cc', '814 cc', '1999 cc',
       '1591 cc', '1397 cc', '1368 cc', '1598 cc', '3198 cc', '1196 cc',
       '2993 cc', '2755 cc', '2143 cc', '2354 cc', '1332 cc', '2199 cc',
       '1997 cc', '1499 cc', '2148 cc', '2696 cc', '1364 cc', '2494 cc',
       '1373 cc', '1299 cc', '1061 cc', '1493 cc', '2497 cc', '1495 cc',
       '1590 cc', '1896 cc', '1330 cc', '1781 cc', '1390 cc', '1194 cc',
       '2953 cc', '1399 cc', '1595 cc', nan, '2496 cc', '0 cc', '1984 cc',
       '2694 cc', '1298 cc', '2362 cc', '970 cc', '2198 cc', '1599 cc',
       '993 cc', '2393 cc', '1389 cc', '1597 cc', '2498 cc', '2523 cc',
       '1586 cc', '995 cc', '2499 cc', '2998 cc', '72 cc', '1589 cc',
       '624 cc', '1596 cc', '799 cc', '3597 cc', '2184 cc', '1405 cc',
       '5000 cc', '1422 cc', '1047 cc', '2200 cc', '2996 cc', '1108 cc',
       '2400 cc', '1996 cc', '1395 cc', '1186 cc', '1799 cc', '2999 cc',
       '1482 cc', '793 cc', '936 cc', '4134 cc', '1796 cc', '1172 cc',
       '1468 cc', '1193 cc', '2477 cc', '2997 cc', '2995 cc', '2487 cc',
       '1794 cc', '3456 cc', '2360 cc', '3982 cc', '2894 cc', '3346 cc',
       '3498 cc', '2979 cc', '1349 cc', '2157 cc', '1985 cc', '2112 cc',
       '2446 cc', '2359 cc', '2609 cc', '2956 cc', '2231 cc', '2835 cc',
       '1150 cc', '1343 cc', '2981 cc', '4395 cc', '1817 cc', '3993 cc',
       '1948 cc', '4806 cc', '2994 cc', '1993 cc', '1490 cc', '2489 cc'],
      dtype=object)

Necessary  columns

In [2]:
import pandas as pd
import os

# Load the CSV file
file_path = "csv_files/structured_cars_data.csv"
df = pd.read_csv(file_path)

# Define the column name mappings
column_mapping = {
    'bt': 'BODY_TYPE',
    'Kms Driven': 'KILOMETERS_DRIVEN',
    'owner': 'NUMBER_OF_OWNERS',
    'Year of Manufacture': 'YEAR_OF_MANUFACTURE',
    'Fuel Type': 'FUEL_TYPE',
    'modelYear': 'MODEL_YEAR',
    'Insurance Validity': 'INSURANCE_VALIDITY',
    'Gear Box': 'NUMBER_OF_GEARS',
    'price': 'PRICE',
    'Mileage': 'MILEAGE',
    'Transmission': 'TRANSMISSION',
    'Seats': 'SEATS',
    'City': 'CITY_NAME'
}

# Create a dictionary for the final column names
new_columns = {}
for old_col in df.columns:
    if old_col in column_mapping:
        new_columns[old_col] = column_mapping[old_col]
    else:
        new_columns[old_col] = old_col  # Keep original case if not in mapping

# Rename the columns in the DataFrame
df_renamed = df.rename(columns=new_columns)

# Define wanted columns (using the *new* names from the mapping, otherwise original case)
wanted_columns_final = [
    'PRICE',
    'BODY_TYPE',
    'KILOMETERS_DRIVEN',
    'NUMBER_OF_OWNERS',
    'YEAR_OF_MANUFACTURE',
    'MILEAGE',
    'FUEL_TYPE',
    'MODEL_YEAR',
    'INSURANCE_VALIDITY',
    'NUMBER_OF_GEARS',
    'TRANSMISSION',
    'SEATS',
    'CITY_NAME'
]

# Filter only the columns that exist in the renamed DataFrame
wanted_columns_present = [col for col in wanted_columns_final if col in df_renamed.columns]

# Select and save the cleaned data
df_cleaned = df_renamed[wanted_columns_present]

# Make sure the output folder exists
os.makedirs("output", exist_ok=True)

# Save the DataFrame to CSV inside the output folder
df_cleaned.to_csv("csv_files/necessary_wanted_cols.csv", index=False)

print("✅ File saved to: output/necessary_wanted_cols.csv")

✅ File saved to: output/necessary_wanted_cols.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_25204\336592845.py:6: DtypeWarning: Columns (14,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,208,209,210,211,212,213,214,215,216,217,218) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [3]:
nan_summary = pd.DataFrame({
    'Column': df_cleaned .columns,
    'Data Type': df_cleaned .dtypes,
    'Non-Null Count': df_cleaned.notna().sum(),
    'NaN Count': df_cleaned .isna().sum(),
    'NaN Percentage': (df_cleaned.isna().mean() * 100).round(2)
}).reset_index(drop=True)

# Display ALL rows without truncation
with pd.option_context('display.max_rows', None, 'display.width', 1000):
    print(nan_summary)

                 Column Data Type  Non-Null Count  NaN Count  NaN Percentage
0                 PRICE    object            8369          0            0.00
1             BODY_TYPE    object            8365          4            0.05
2     KILOMETERS_DRIVEN    object            8367          2            0.02
3      NUMBER_OF_OWNERS    object            8369          0            0.00
4   YEAR_OF_MANUFACTURE   float64            8349         20            0.24
5               MILEAGE    object            8082        287            3.43
6             FUEL_TYPE    object            8369          0            0.00
7            MODEL_YEAR     int64            8369          0            0.00
8    INSURANCE_VALIDITY    object            8365          4            0.05
9       NUMBER_OF_GEARS    object            8263        106            1.27
10         TRANSMISSION    object            8369          0            0.00
11                SEATS    object            8363          6            0.07
12            CITY_NAME    object            8369          0            0.00

***b)Handling Missing Values:***

 Identify and fill or remove missing values in the dataset. 

i)	For numerical columns, use techniques like mean, median, or mode imputation.

ii)	For categorical columns, use mode imputation or create a new category for missing values.

In [32]:
import pandas as pd
import numpy as np
import os

# Load the dataset
df = pd.read_csv("csv_files/necessary_wanted_cols.csv")

# Function to print missing value statistics
def print_missing_stats(df, title="Before Imputation"):
    print(f"\n🔍 {title} Missing Values Summary:")
    print("="*60)
    missing_data = df.isnull().sum()
    total_rows = len(df)
    missing_percent = (missing_data / total_rows) * 100

    stats_df = pd.DataFrame({
        'Missing Values': missing_data,
        '% Missing': missing_percent.round(2)
    })

    print(stats_df[stats_df['Missing Values'] > 0].sort_values('% Missing', ascending=False))
    print("="*60)
    print(f"Total rows in dataset: {total_rows}\n")

# Initial missing value analysis
print_missing_stats(df)

# Create a copy for tracking changes
df_cleaned_filled = df.copy()

# Dictionary to store imputation details
imputation_report = {}

# Handle numerical columns
numerical_cols = ['YEAR_OF_MANUFACTURE']
for col in numerical_cols:
    if col in df_cleaned_filled.columns:
        before = df_cleaned_filled[col].isnull().sum()
        median_val = df_cleaned_filled[col].median()
        df_cleaned_filled[col].fillna(median_val, inplace=True)
        after = df_cleaned_filled[col].isnull().sum()

        imputation_report[col] = {
            'type': 'numerical',
            'before': before,
            'filled': before - after,
            'method': 'median',
            'value': median_val,
            'justification': 'Median is robust against outliers in manufacturing years'
        }

# Handle categorical columns
categorical_cols = ['COLOR', 'REGISTRATION_YEAR', 'INSURANCE_VALIDITY',
                    'NUMBER_OF_GEARS', 'SEATS', 'ENGINE DISPLACEMENT', 'MILEAGE']

for col in categorical_cols:
    if col in df_cleaned_filled.columns:
        before = df_cleaned_filled[col].isnull().sum()
        mode_val = df_cleaned_filled[col].mode()[0]
        df_cleaned_filled[col].fillna(mode_val, inplace=True)
        after = df_cleaned_filled[col].isnull().sum()

        imputation_report[col] = {
            'type': 'categorical',
            'before': before,
            'filled': before - after,
            'method': 'mode',
            'value': mode_val,
            'justification': 'Most frequent value is appropriate for categorical data'
        }

# Special handling for 'MILEAGE' column
if 'MILEAGE' in df_cleaned_filled.columns:
    # Extract numerical part from Mileage (e.g., '23.1 kmpl' -> 23.1)
    df_cleaned_filled['MILEAGE'] = df_cleaned_filled['MILEAGE'].str.extract('(\d+\.?\d*)').astype(float)

    before = df_cleaned_filled['MILEAGE'].isnull().sum()
    median_mileage = df_cleaned_filled['MILEAGE'].median()
    df_cleaned_filled['MILEAGE'].fillna(median_mileage, inplace=True)
    after = df_cleaned_filled['MILEAGE'].isnull().sum()

    imputation_report['MILEAGE'] = {
        'type': 'converted numerical',
        'before': before,
        'filled': before - after,
        'method': 'median',
        'value': median_mileage,
        'justification': 'After converting string to numerical, median is robust for mileage values'
    }

# Final missing value analysis
print_missing_stats(df_cleaned_filled, "After Imputation")

# Generate imputation report
print("\n✅ Imputation Summary")
print("="*60)
print("Here's a breakdown of how missing values were handled in your dataset:")
print("-"*60)

if imputation_report:  # Check if the dictionary is not empty
    report_df = pd.DataFrame.from_dict(imputation_report, orient='index')
    # Ensure the expected columns exist before selection
    expected_columns = ['type', 'before', 'filled', 'method', 'value', 'justification']
    existing_columns = report_df.columns.tolist()
    columns_to_select = [col for col in expected_columns if col in existing_columns]

    if columns_to_select:
        report_df = report_df[columns_to_select]
        report_df.columns = ['Type', 'Missing Before', 'Filled', 'Strategy', 'Value Used', 'Justification']
        print(report_df.sort_values('Missing Before', ascending=False))
    else:
        print("No missing values were imputed, so no imputation report to display.")
else:
    print("No missing values were found in the dataset.")

print("="*60)

# Detect and print data types
print("\n🔎 Final Data Types:")
print("="*60)
print(df_cleaned_filled.dtypes)
print("="*60)

# Create a copy to detect data types without modifying the original
df_detected_dtypes = df_cleaned_filled.copy().convert_dtypes()

print("Original DataFrame dtypes:")
print(df_cleaned_filled.dtypes)
print("\nDetected dtypes (without saving):")
print(df_detected_dtypes.dtypes)
print("\nAutomatically detected the datatypes (in the copy)")

#  replace it here

# Save the cleaned data with detected data types
os.makedirs("csv_files", exist_ok=True)
output_path = "csv_files/cars_filled_removed.csv"
df_detected_dtypes.to_csv(output_path, index=False)

# print(f"\n✅ Cleaned dataset saved to: {output_path}")

🔍 Before Imputation Missing Values Summary:
============================================================
                     Missing Values  % Missing
MILEAGE                         287       3.43
NUMBER_OF_GEARS                 106       1.27
YEAR_OF_MANUFACTURE              20       0.24
SEATS                             6       0.07
BODY_TYPE                         4       0.05
INSURANCE_VALIDITY                4       0.05
KILOMETERS_DRIVEN                 2       0.02
============================================================
Total rows in dataset: 8369


🔍 After Imputation Missing Values Summary:
============================================================
                   Missing Values  % Missing
BODY_TYPE                       4       0.05
KILOMETERS_DRIVEN               2       0.02
============================================================
Total rows in dataset: 8369


✅ Imputation Summary
============================================================
Here's a breakdown of how missing values were handled in your dataset:
------------------------------------------------------------
                                    Type  Missing Before  Filled Strategy  \
NUMBER_OF_GEARS              categorical             106     106     mode
YEAR_OF_MANUFACTURE            numerical              20      20   median
SEATS                        categorical               6       6     mode
INSURANCE_VALIDITY           categorical               4       4     mode
MILEAGE              converted numerical               0       0   median

                                Value Used  \
NUMBER_OF_GEARS                    5 Speed
YEAR_OF_MANUFACTURE                 2017.0
SEATS                              5 Seats
INSURANCE_VALIDITY   Third Party insurance
MILEAGE                               18.9

                                                         Justification
NUMBER_OF_GEARS      Most frequent value is appropriate for categor...
YEAR_OF_MANUFACTURE  Median is robust against outliers in manufactu...
SEATS                Most frequent value is appropriate for categor...
INSURANCE_VALIDITY   Most frequent value is appropriate for categor...
MILEAGE              After converting string to numerical, median i...
============================================================

🔎 Final Data Types:
============================================================
PRICE                   object
BODY_TYPE               object
KILOMETERS_DRIVEN       object
NUMBER_OF_OWNERS        object
YEAR_OF_MANUFACTURE    float64
MILEAGE                float64
FUEL_TYPE               object
MODEL_YEAR               int64
INSURANCE_VALIDITY      object
NUMBER_OF_GEARS         object
TRANSMISSION            object
SEATS                   object
CITY_NAME               object
dtype: object
============================================================
Original DataFrame dtypes:
PRICE                   object
BODY_TYPE               object
KILOMETERS_DRIVEN       object
NUMBER_OF_OWNERS        object
YEAR_OF_MANUFACTURE    float64
MILEAGE                float64
FUEL_TYPE               object
MODEL_YEAR               int64
INSURANCE_VALIDITY      object
NUMBER_OF_GEARS         object
TRANSMISSION            object
SEATS                   object
CITY_NAME               object
dtype: object

Detected dtypes (without saving):
PRICE                  string[python]
BODY_TYPE              string[python]
KILOMETERS_DRIVEN      string[python]
NUMBER_OF_OWNERS       string[python]
YEAR_OF_MANUFACTURE             Int64
MILEAGE                       Float64
FUEL_TYPE              string[python]
MODEL_YEAR                      Int64
INSURANCE_VALIDITY     string[python]
NUMBER_OF_GEARS        string[python]
TRANSMISSION           string[python]
SEATS                  string[python]
CITY_NAME              string[python]
dtype: object

Automatically detected the datatypes (in the copy)

C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3120422852.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(median_val, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3120422852.py:60: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(mode_val, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3120422852.py:79: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled['MILEAGE'].fillna(median_mileage, inplace=True)

In [33]:
nan_summary = pd.DataFrame({
    'Column': df_detected_dtypes .columns,
    'Data Type': df_detected_dtypes .dtypes,
    'Non-Null Count': df_detected_dtypes.notna().sum(),
    'NaN Count': df_detected_dtypes .isna().sum(),
    'NaN Percentage': (df_detected_dtypes.isna().mean() * 100).round(2)
}).reset_index(drop=True)

# Display ALL rows without truncation
with pd.option_context('display.max_rows', None, 'display.width', 1000):
    print(nan_summary)

                 Column       Data Type  Non-Null Count  NaN Count  NaN Percentage
0                 PRICE  string[python]            8369          0            0.00
1             BODY_TYPE  string[python]            8365          4            0.05
2     KILOMETERS_DRIVEN  string[python]            8367          2            0.02
3      NUMBER_OF_OWNERS  string[python]            8369          0            0.00
4   YEAR_OF_MANUFACTURE           Int64            8369          0            0.00
5               MILEAGE         Float64            8369          0            0.00
6             FUEL_TYPE  string[python]            8369          0            0.00
7            MODEL_YEAR           Int64            8369          0            0.00
8    INSURANCE_VALIDITY  string[python]            8369          0            0.00
9       NUMBER_OF_GEARS  string[python]            8369          0            0.00
10         TRANSMISSION  string[python]            8369          0            0.00
11                SEATS  string[python]            8369          0            0.00
12            CITY_NAME  string[python]            8369          0            0.00

In [ ]:
# Define the columns to check for NaNs or blanks
columns_to_check = [
    'PRICE',
    'BODY_TYPE',
    'KILOMETERS_DRIVEN',
    'NUMBER_OF_OWNERS',
    'YEAR_OF_MANUFACTURE',
    'MILEAGE',
    'FUEL_TYPE',
    'REGISTRATION_YEAR',
    'MODEL_YEAR',
    'INSURANCE_VALIDITY',
    'NUMBER_OF_GEARS',
    'TRANSMISSION',
    'SEATS',
    'CITY_NAME'
]

# Identify rows with NaN or blank in the specified columns
rows_to_drop = set()
for col in columns_to_check:
    if col in df.columns:  # Assuming your DataFrame is named 'df'
        nan_rows = df[df[col].isna()].index
        blank_rows = df[df[col].astype(str).str.strip() == ''].index
        rows_to_drop.update(nan_rows)
        rows_to_drop.update(blank_rows)

rows_to_drop = sorted(list(rows_to_drop))

# Drop the identified rows
if rows_to_drop:
    print(f"\n⚠️ Dropping {len(rows_to_drop)} rows with NaN or blank values in the specified columns.")
    df.drop(index=rows_to_drop, inplace=True)  # Assuming your DataFrame is named 'df'
else:
    print("\n✅ No rows with NaN or blank values found in the specified columns.")

check_please

In [8]:
import pandas as pd
import numpy as np
import os

# Load the dataset
df = pd.read_csv("csv_files/necessary_wanted_cols.csv")

# Function to print missing value statistics
def print_missing_stats(df, title="Before Imputation"):
    print(f"\n🔍 {title} Missing Values Summary:")
    print("="*60)
    missing_data = df.isnull().sum()
    total_rows = len(df)
    missing_percent = (missing_data / total_rows) * 100

    stats_df = pd.DataFrame({
        'Missing Values': missing_data,
        '% Missing': missing_percent.round(2)
    })

    print(stats_df[stats_df['Missing Values'] > 0].sort_values('% Missing', ascending=False))
    print("="*60)
    print(f"Total rows in dataset: {total_rows}\n")

# Initial missing value analysis
print_missing_stats(df)

# Create a copy for tracking changes
df_cleaned_filled = df.copy()

# Dictionary to store imputation details
imputation_report = {}

# Handle numerical columns
numerical_cols_to_fill = ['YEAR_OF_MANUFACTURE', 'KILOMETERS_DRIVEN']
for col in numerical_cols_to_fill:
    if col in df_cleaned_filled.columns:
        # Attempt to convert to numeric, errors='coerce' will turn non-numeric to NaN
        df_cleaned_filled[col] = pd.to_numeric(df_cleaned_filled[col], errors='coerce')
        before = df_cleaned_filled[col].isnull().sum()
        median_val = df_cleaned_filled[col].median()
        df_cleaned_filled[col].fillna(median_val, inplace=True)
        after = df_cleaned_filled[col].isnull().sum()

        imputation_report[col] = {
            'type': 'numerical',
            'before': before,
            'filled': before - after,
            'method': 'median',
            'value': median_val,
            'justification': f'Converted to numeric and filled with median due to potential non-numeric entries.'
        }

# Handle categorical columns
categorical_cols_to_fill = ['COLOR', 'REGISTRATION_YEAR', 'INSURANCE_VALIDITY',
                            'NUMBER_OF_GEARS', 'SEATS', 'ENGINE DISPLACEMENT', 'MILEAGE', 'BODY_TYPE']

for col in categorical_cols_to_fill:
    if col in df_cleaned_filled.columns:
        before = df_cleaned_filled[col].isnull().sum()
        # Handle potential errors if mode is empty
        try:
            mode_val = df_cleaned_filled[col].mode()[0]
            df_cleaned_filled[col].fillna(mode_val, inplace=True)
            after = df_cleaned_filled[col].isnull().sum()
            imputation_report[col] = {
                'type': 'categorical',
                'before': before,
                'filled': before - after,
                'method': 'mode',
                'value': mode_val,
                'justification': 'Filled with the most frequent value.'
            }
        except IndexError:
            print(f"Warning: Cannot fill NaN in '{col}' as the mode is not available (all values might be NaN).")
            imputation_report[col] = {
                'type': 'categorical',
                'before': before,
                'filled': 0,
                'method': 'none',
                'value': None,
                'justification': 'Mode not available.'
            }

# Special handling for 'MILEAGE' column
if 'MILEAGE' in df_cleaned_filled.columns:
    # Extract numerical part from Mileage (e.g., '23.1 kmpl' -> 23.1)
    df_cleaned_filled['MILEAGE'] = df_cleaned_filled['MILEAGE'].str.extract('(\d+\.?\d*)').astype(float)

    before = df_cleaned_filled['MILEAGE'].isnull().sum()
    median_mileage = df_cleaned_filled['MILEAGE'].median()
    df_cleaned_filled['MILEAGE'].fillna(median_mileage, inplace=True)
    after = df_cleaned_filled['MILEAGE'].isnull().sum()

    imputation_report['MILEAGE'] = {
        'type': 'converted numerical',
        'before': before,
        'filled': before - after,
        'method': 'median',
        'value': median_mileage,
        'justification': 'After converting string to numerical, median is robust for mileage values'
    }

# Final missing value analysis
print_missing_stats(df_cleaned_filled, "After Imputation")

# Generate imputation report
print("\n✅ Imputation Summary")
print("="*60)
print("Here's a breakdown of how missing values were handled in your dataset:")
print("-"*60)

if imputation_report:
    report_df = pd.DataFrame.from_dict(imputation_report, orient='index')
    expected_columns = ['type', 'before', 'filled', 'method', 'value', 'justification']
    existing_columns = report_df.columns.tolist()
    columns_to_select = [col for col in expected_columns if col in existing_columns]

    if columns_to_select:
        report_df = report_df[columns_to_select]
        report_df.columns = ['Type', 'Missing Before', 'Filled', 'Strategy', 'Value Used', 'Justification']
        print(report_df.sort_values('Missing Before', ascending=False))
    else:
        print("No missing values were imputed, so no imputation report to display.")
else:
    print("No missing values were found in the dataset.")

print("="*60)

# Detect and print data types
print("\n🔎 Final Data Types:")
print("="*60)
print(df_cleaned_filled.dtypes)
print("="*60)

# Create a copy to detect data types without modifying the original
df_detected_dtypes = df_cleaned_filled.copy().convert_dtypes()

print("Original DataFrame dtypes:")
print(df_cleaned_filled.dtypes)
print("\nDetected dtypes (without saving):")
print(df_detected_dtypes.dtypes)
print("\nAutomatically detected the datatypes (in the copy)")

# Save the cleaned data with detected data types
os.makedirs("csv_files", exist_ok=True)
output_path = "csv_files/cars_filled_removed.csv"
df_detected_dtypes.to_csv(output_path, index=False)

print(f"\n✅ Cleaned dataset saved to: {output_path}")

🔍 Before Imputation Missing Values Summary:
============================================================
                     Missing Values  % Missing
MILEAGE                         287       3.43
NUMBER_OF_GEARS                 106       1.27
YEAR_OF_MANUFACTURE              20       0.24
SEATS                             6       0.07
BODY_TYPE                         4       0.05
INSURANCE_VALIDITY                4       0.05
KILOMETERS_DRIVEN                 2       0.02
============================================================
Total rows in dataset: 8369


🔍 After Imputation Missing Values Summary:
============================================================
                   Missing Values  % Missing
KILOMETERS_DRIVEN            8369      100.0
============================================================
Total rows in dataset: 8369


✅ Imputation Summary
============================================================
Here's a breakdown of how missing values were handled in your dataset:
------------------------------------------------------------
                                    Type  Missing Before  Filled Strategy  \
KILOMETERS_DRIVEN              numerical            8369       0   median
NUMBER_OF_GEARS              categorical             106     106     mode
YEAR_OF_MANUFACTURE            numerical              20      20   median
SEATS                        categorical               6       6     mode
INSURANCE_VALIDITY           categorical               4       4     mode
BODY_TYPE                    categorical               4       4     mode
MILEAGE              converted numerical               0       0   median

                                Value Used  \
KILOMETERS_DRIVEN                      NaN
NUMBER_OF_GEARS                    5 Speed
YEAR_OF_MANUFACTURE                 2017.0
SEATS                              5 Seats
INSURANCE_VALIDITY   Third Party insurance
BODY_TYPE                        Hatchback
MILEAGE                               18.9

                                                         Justification
KILOMETERS_DRIVEN    Converted to numeric and filled with median du...
NUMBER_OF_GEARS                   Filled with the most frequent value.
YEAR_OF_MANUFACTURE  Converted to numeric and filled with median du...
SEATS                             Filled with the most frequent value.
INSURANCE_VALIDITY                Filled with the most frequent value.
BODY_TYPE                         Filled with the most frequent value.
MILEAGE              After converting string to numerical, median i...
============================================================

🔎 Final Data Types:
============================================================
PRICE                   object
BODY_TYPE               object
KILOMETERS_DRIVEN      float64
NUMBER_OF_OWNERS        object
YEAR_OF_MANUFACTURE    float64
MILEAGE                float64
FUEL_TYPE               object
MODEL_YEAR               int64
INSURANCE_VALIDITY      object
NUMBER_OF_GEARS         object
TRANSMISSION            object
SEATS                   object
CITY_NAME               object
dtype: object
============================================================
Original DataFrame dtypes:
PRICE                   object
BODY_TYPE               object
KILOMETERS_DRIVEN      float64
NUMBER_OF_OWNERS        object
YEAR_OF_MANUFACTURE    float64
MILEAGE                float64
FUEL_TYPE               object
MODEL_YEAR               int64
INSURANCE_VALIDITY      object
NUMBER_OF_GEARS         object
TRANSMISSION            object
SEATS                   object
CITY_NAME               object
dtype: object

Detected dtypes (without saving):
PRICE                  string[python]
BODY_TYPE              string[python]
KILOMETERS_DRIVEN               Int64
NUMBER_OF_OWNERS       string[python]
YEAR_OF_MANUFACTURE             Int64
MILEAGE                       Float64
FUEL_TYPE              string[python]
MODEL_YEAR                      Int64
INSURANCE_VALIDITY     string[python]
NUMBER_OF_GEARS        string[python]
TRANSMISSION           string[python]
SEATS                  string[python]
CITY_NAME              string[python]
dtype: object

Automatically detected the datatypes (in the copy)

✅ Cleaned dataset saved to: csv_files/cars_filled_removed.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3501016970.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(median_val, inplace=True)
c:\Users\USER\Desktop\Car-Dheko_Used_Car_Price_Prediction\.venv\lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3501016970.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(median_val, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3501016970.py:64: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(mode_val, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3501016970.py:92: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled['MILEAGE'].fillna(median_mileage, inplace=True)

In [10]:
import pandas as pd
import numpy as np
import os

# Load the dataset
df = pd.read_csv("csv_files/necessary_wanted_cols.csv")

# Print info before any processing
print("\n--- Info Before Processing 'KILOMETERS_DRIVEN' ---")
print(df['KILOMETERS_DRIVEN'].info())
print("\n--- Unique Values in 'KILOMETERS_DRIVEN' ---")
print(df['KILOMETERS_DRIVEN'].unique()[:50]) # Display the first 50 unique values
print("\n--- Value Counts of 'KILOMETERS_DRIVEN' ---")
print(df['KILOMETERS_DRIVEN'].value_counts().head(20)) # Display the top 20 most frequent values

# Create a copy for tracking changes
df_cleaned_filled = df.copy()

# Dictionary to store imputation details
imputation_report = {}

# Handle numerical columns
numerical_cols_to_fill = ['YEAR_OF_MANUFACTURE', 'KILOMETERS_DRIVEN']
for col in numerical_cols_to_fill:
    if col in df_cleaned_filled.columns:
        print(f"\n--- Processing column: {col} ---")
        # Attempt to convert to numeric, errors='coerce' will turn non-numeric to NaN
        df_cleaned_filled[col] = pd.to_numeric(df_cleaned_filled[col], errors='coerce')
        before = df_cleaned_filled[col].isnull().sum()
        median_val = df_cleaned_filled[col].median()
        df_cleaned_filled[col].fillna(median_val, inplace=True)
        after = df_cleaned_filled[col].isnull().sum()

        imputation_report[col] = {
            'type': 'numerical',
            'before': before,
            'filled': before - after,
            'method': 'median',
            'value': median_val,
            'justification': f'Converted to numeric and filled with median due to potential non-numeric entries.'
        }

# Handle categorical columns
categorical_cols_to_fill = ['COLOR', 'REGISTRATION_YEAR', 'INSURANCE_VALIDITY',
                            'NUMBER_OF_GEARS', 'SEATS', 'ENGINE DISPLACEMENT', 'MILEAGE', 'BODY_TYPE']

for col in categorical_cols_to_fill:
    if col in df_cleaned_filled.columns:
        before = df_cleaned_filled[col].isnull().sum()
        try:
            mode_val = df_cleaned_filled[col].mode()[0]
            df_cleaned_filled[col].fillna(mode_val, inplace=True)
            after = df_cleaned_filled[col].isnull().sum()
            imputation_report[col] = {
                'type': 'categorical',
                'before': before,
                'filled': before - after,
                'method': 'mode',
                'value': mode_val,
                'justification': 'Filled with the most frequent value.'
            }
        except IndexError:
            print(f"Warning: Cannot fill NaN in '{col}' as the mode is not available (all values might be NaN).")
            imputation_report[col] = {
                'type': 'categorical',
                'before': before,
                'filled': 0,
                'method': 'none',
                'value': None,
                'justification': 'Mode not available.'
            }

# Special handling for 'MILEAGE' column
if 'MILEAGE' in df_cleaned_filled.columns:
    # Extract numerical part from Mileage (e.g., '23.1 kmpl' -> 23.1)
    df_cleaned_filled['MILEAGE'] = df_cleaned_filled['MILEAGE'].str.extract('(\d+\.?\d*)').astype(float)

    before = df_cleaned_filled['MILEAGE'].isnull().sum()
    median_mileage = df_cleaned_filled['MILEAGE'].median()
    df_cleaned_filled['MILEAGE'].fillna(median_mileage, inplace=True)
    after = df_cleaned_filled['MILEAGE'].isnull().sum()

    imputation_report['MILEAGE'] = {
        'type': 'converted numerical',
        'before': before,
        'filled': before - after,
        'method': 'median',
        'value': median_mileage,
        'justification': 'After converting string to numerical, median is robust for mileage values'
    }

# Final missing value analysis
print_missing_stats(df_cleaned_filled, "After Imputation")

# Generate imputation report
print("\n✅ Imputation Summary")
print("="*60)
print("Here's a breakdown of how missing values were handled in your dataset:")
print("-"*60)

if imputation_report:
    report_df = pd.DataFrame.from_dict(imputation_report, orient='index')
    expected_columns = ['type', 'before', 'filled', 'method', 'value', 'justification']
    existing_columns = report_df.columns.tolist()
    columns_to_select = [col for col in expected_columns if col in existing_columns]

    if columns_to_select:
        report_df = report_df[columns_to_select]
        report_df.columns = ['Type', 'Missing Before', 'Filled', 'Strategy', 'Value Used', 'Justification']
        print(report_df.sort_values('Missing Before', ascending=False))
    else:
        print("No missing values were imputed, so no imputation report to display.")
else:
    print("No missing values were found in the dataset.")

print("="*60)

# Detect and print data types
print("\n🔎 Final Data Types:")
print("="*60)
print(df_cleaned_filled.dtypes)
print("="*60)

# Create a copy to detect data types without modifying the original
df_detected_dtypes = df_cleaned_filled.copy().convert_dtypes()

print("Original DataFrame dtypes:")
print(df_cleaned_filled.dtypes)
print("\nDetected dtypes (without saving):")
print(df_detected_dtypes.dtypes)
print("\nAutomatically detected the datatypes (in the copy)")

# Save the cleaned data with detected data types
os.makedirs("csv_files", exist_ok=True)
output_path = "csv_files/cars_filled_removed.csv"
df_detected_dtypes.to_csv(output_path, index=False)

print(f"\n✅ Cleaned dataset saved to: {output_path}")

--- Info Before Processing 'KILOMETERS_DRIVEN' ---
<class 'pandas.core.series.Series'>
RangeIndex: 8369 entries, 0 to 8368
Series name: KILOMETERS_DRIVEN
Non-Null Count  Dtype
--------------  -----
8367 non-null   object
dtypes: object(1)
memory usage: 65.5+ KB
None

--- Unique Values in 'KILOMETERS_DRIVEN' ---
['1,20,000 Kms' '32,706 Kms' '11,949 Kms' '17,794 Kms' '60,000 Kms'
 '20,000 Kms' '37,772 Kms' '30,000 Kms' '37,000 Kms' '50,000 Kms'
 '24,887 Kms' '23,000 Kms' '48,928 Kms' '1,08,862 Kms' '80,000 Kms'
 '16,000 Kms' '65,376 Kms' '10,000 Kms' '67,000 Kms' '1,00,000 Kms'
 '18,083 Kms' '57,634 Kms' '1,10,000 Kms' '23,447 Kms' '33,000 Kms'
 '87,667 Kms' '40,000 Kms' '79,012 Kms' '31,344 Kms' '12,434 Kms'
 '12,000 Kms' '40,987 Kms' '18,157 Kms' '89,667 Kms' '56,997 Kms'
 '59,000 Kms' '18,835 Kms' '60,932 Kms' '33,539 Kms' '66,837 Kms'
 '400 Kms' '44,285 Kms' '25,000 Kms' '36,735 Kms' '79,000 Kms'
 '53,645 Kms' '53,982 Kms' '37,741 Kms' '17,367 Kms' '94,000 Kms']

--- Value Counts of 'KILOMETERS_DRIVEN' ---
KILOMETERS_DRIVEN
1,20,000 Kms    315
50,000 Kms      263
70,000 Kms      262
60,000 Kms      259
30,000 Kms      253
20,000 Kms      252
40,000 Kms      242
80,000 Kms      228
10,000 Kms      212
90,000 Kms      170
1,00,000 Kms    160
1,50,000 Kms     96
1,10,000 Kms     90
45,000 Kms       49
65,000 Kms       45
55,000 Kms       41
75,000 Kms       34
34,000 Kms       31
68,000 Kms       29
35,000 Kms       28
Name: count, dtype: int64

--- Processing column: YEAR_OF_MANUFACTURE ---

--- Processing column: KILOMETERS_DRIVEN ---

🔍 After Imputation Missing Values Summary:
============================================================
                   Missing Values  % Missing
KILOMETERS_DRIVEN            8369      100.0
============================================================
Total rows in dataset: 8369


✅ Imputation Summary
============================================================
Here's a breakdown of how missing values were handled in your dataset:
------------------------------------------------------------
                                    Type  Missing Before  Filled Strategy  \
KILOMETERS_DRIVEN              numerical            8369       0   median
NUMBER_OF_GEARS              categorical             106     106     mode
YEAR_OF_MANUFACTURE            numerical              20      20   median
SEATS                        categorical               6       6     mode
INSURANCE_VALIDITY           categorical               4       4     mode
BODY_TYPE                    categorical               4       4     mode
MILEAGE              converted numerical               0       0   median

                                Value Used  \
KILOMETERS_DRIVEN                      NaN
NUMBER_OF_GEARS                    5 Speed
YEAR_OF_MANUFACTURE                 2017.0
SEATS                              5 Seats
INSURANCE_VALIDITY   Third Party insurance
BODY_TYPE                        Hatchback
MILEAGE                               18.9

                                                         Justification
KILOMETERS_DRIVEN    Converted to numeric and filled with median du...
NUMBER_OF_GEARS                   Filled with the most frequent value.
YEAR_OF_MANUFACTURE  Converted to numeric and filled with median du...
SEATS                             Filled with the most frequent value.
INSURANCE_VALIDITY                Filled with the most frequent value.
BODY_TYPE                         Filled with the most frequent value.
MILEAGE              After converting string to numerical, median i...
============================================================

🔎 Final Data Types:
============================================================
PRICE                   object
BODY_TYPE               object
KILOMETERS_DRIVEN      float64
NUMBER_OF_OWNERS        object
YEAR_OF_MANUFACTURE    float64
MILEAGE                float64
FUEL_TYPE               object
MODEL_YEAR               int64
INSURANCE_VALIDITY      object
NUMBER_OF_GEARS         object
TRANSMISSION            object
SEATS                   object
CITY_NAME               object
dtype: object
============================================================
Original DataFrame dtypes:
PRICE                   object
BODY_TYPE               object
KILOMETERS_DRIVEN      float64
NUMBER_OF_OWNERS        object
YEAR_OF_MANUFACTURE    float64
MILEAGE                float64
FUEL_TYPE               object
MODEL_YEAR               int64
INSURANCE_VALIDITY      object
NUMBER_OF_GEARS         object
TRANSMISSION            object
SEATS                   object
CITY_NAME               object
dtype: object

Detected dtypes (without saving):
PRICE                  string[python]
BODY_TYPE              string[python]
KILOMETERS_DRIVEN               Int64
NUMBER_OF_OWNERS       string[python]
YEAR_OF_MANUFACTURE             Int64
MILEAGE                       Float64
FUEL_TYPE              string[python]
MODEL_YEAR                      Int64
INSURANCE_VALIDITY     string[python]
NUMBER_OF_GEARS        string[python]
TRANSMISSION           string[python]
SEATS                  string[python]
CITY_NAME              string[python]
dtype: object

Automatically detected the datatypes (in the copy)

✅ Cleaned dataset saved to: csv_files/cars_filled_removed.csv

C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3937719871.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(median_val, inplace=True)
c:\Users\USER\Desktop\Car-Dheko_Used_Car_Price_Prediction\.venv\lib\site-packages\numpy\lib\_nanfunctions_impl.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3937719871.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(median_val, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3937719871.py:52: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled[col].fillna(mode_val, inplace=True)
C:\Users\USER\AppData\Local\Temp\ipykernel_25204\3937719871.py:80: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned_filled['MILEAGE'].fillna(median_mileage, inplace=True)

In [12]:
nan_summary = pd.DataFrame({
    'Column': df_detected_dtypes .columns,
    'Data Type': df_detected_dtypes .dtypes,
    'Non-Null Count': df_detected_dtypes.notna().sum(),
    'NaN Count': df_detected_dtypes .isna().sum(),
    'NaN Percentage': (df_detected_dtypes.isna().mean() * 100).round(2)
}).reset_index(drop=True)

# Display ALL rows without truncation
with pd.option_context('display.max_rows', None, 'display.width', 1000):
    print(nan_summary)

                 Column       Data Type  Non-Null Count  NaN Count  NaN Percentage
0                 PRICE  string[python]            8369          0             0.0
1             BODY_TYPE  string[python]            8369          0             0.0
2     KILOMETERS_DRIVEN           Int64               0       8369           100.0
3      NUMBER_OF_OWNERS  string[python]            8369          0             0.0
4   YEAR_OF_MANUFACTURE           Int64            8369          0             0.0
5               MILEAGE         Float64            8369          0             0.0
6             FUEL_TYPE  string[python]            8369          0             0.0
7            MODEL_YEAR           Int64            8369          0             0.0
8    INSURANCE_VALIDITY  string[python]            8369          0             0.0
9       NUMBER_OF_GEARS  string[python]            8369          0             0.0
10         TRANSMISSION  string[python]            8369          0             0.0
11                SEATS  string[python]            8369          0             0.0
12            CITY_NAME  string[python]            8369          0             0.0

***c)	Standardising Data Formats:***

i)	Check for all data types and do the necessary steps to keep the data in the correct format.

(1)	Eg. If a data point has string formats like 70 kms, then remove the unit ‘kms’ and change the data type from string to integers.

In [6]:
df_detected_dtypes.head()

,price,bt,Kms Driven,owner,Year of Manufacture,Mileage,RTO,Fuel Type,Registration Year,modelYear,Insurance Validity,Gear Box,Transmission,Seats,City,Engine Displacement
0,₹ 4 Lakh,Hatchback,"1,20,000 Kms",3rd Owner,2015,23.1,KA51,Petrol,2015,2015,Third Party insurance,5 Speed,Manual,5 Seats,bangalore,998 cc
1,₹ 8.11 Lakh,SUV,"32,706 Kms",2nd Owner,2018,17.0,KA05,Petrol,Feb 2018,2018,Comprehensive,5 Speed,Manual,5 Seats,bangalore,1497 cc
2,₹ 5.85 Lakh,Hatchback,"11,949 Kms",1st Owner,2018,23.84,KA03,Petrol,Sept 2018,2018,Comprehensive,5 Speed,Manual,5 Seats,bangalore,1199 cc
3,₹ 4.62 Lakh,Sedan,"17,794 Kms",1st Owner,2014,19.1,KA53,Petrol,Dec 2014,2014,Comprehensive,5 Speed,Manual,5 Seats,bangalore,1197 cc
4,₹ 7.90 Lakh,SUV,"60,000 Kms",1st Owner,2015,23.65,KA04,Diesel,2015,2015,Third Party insurance,5 Speed,Manual,5 Seats,bangalore,1248 cc

| Transmission Type | Gear Number        | Justification                                                                                                                                                              |
|-------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| CVT               | Theoretically Infinite | Uses a belt and pulley (or cone) system that continuously adjusts the ratio, offering a seamless and theoretically infinite number of gear ratios within its operating range. |
| Direct Drive      | Typically One (1:1) | Represents a single, direct connection where the input and output shafts rotate at the same speed, with no gear reduction or multiplication.                               |
| IVT               | Theoretically Infinite | Hyundai/Kia's marketing term for their CVT technology, functioning on the same principle of continuous ratio adjustment via a belt and pulley system.                   |
| iMT               | Fixed (e.g., 5 or 6) | A manual transmission with a traditional set of physical gears. The electronic system automates the clutch, but the number of selectable gears remains fixed.             |
| AGS               | Fixed (e.g., 5)    | An automated manual transmission that uses a traditional set of physical gears. The system automates both clutch operation and gear selection, but the number of gears is fixed. |

In [10]:
import pandas as pd
from decimal import Decimal
import os
import re


try:
    df_standardised = pd.read_csv("output/banglore_filled_removed.csv")  # Ensure correct file name
except FileNotFoundError:
    print("Error: The file 'output/banglore_filled_removed.csv' was not found.")
    exit()


def clean_numeric_column(series, pattern=None, dtype=float):
    """Helper function to clean numeric columns"""
    try:
        if series.dtype == object:
            if pattern:
                extracted = series.str.extract(pattern)[0]
            else:
                extracted = series.astype(str).str.replace(r'[^\d\.]', '', regex=True) # Keep decimals
            if dtype == 'Int64':
                return pd.to_numeric(extracted, errors='coerce').astype('Int64')
            return pd.to_numeric(extracted, errors='coerce')
        return series
    except Exception as e:
        print(f"⚠️ Warning cleaning column {series.name}: {e}")
        return series
    
def clean_numeric_series(series, dtype=float, pattern=None):
    """Clean a pandas Series containing numeric values"""
    try:
        if not pd.api.types.is_string_dtype(series):
            series = series.astype(str)
            
        # Remove commas and extract numeric values
        cleaned = series.str.replace(',', '')
        
        if pattern:
            extracted = cleaned.str.extract(pattern)[0]
        else:
            if dtype == float:
                extracted = cleaned.str.extract(r'([\d\.]+)')[0]
            else:
                extracted = cleaned.str.extract(r'(\d+)')[0]
        
        # Convert to appropriate type
        if dtype == 'Int64':
            return pd.to_numeric(extracted, errors='coerce').astype('Int64')
        return pd.to_numeric(extracted, errors='coerce').astype(dtype)
    except Exception as e:
        print(f"⚠️ Warning cleaning numeric series: {e}")
        return series
    
def clean_kms_driven(kms_str):
    """
    Cleans the 'Kms Driven' string by removing non-numeric characters
    and converting it to an integer.
    Handles cases with commas and the "Kms" suffix.
    Returns the cleaned number as an integer or None if cleaning fails.
    """
    if isinstance(kms_str, (int, float)):
        return int(kms_str)  # Already numeric

    cleaned_str = re.sub(r'[^\d]', '', str(kms_str))  # Remove non-digits
    if cleaned_str:
        return int(cleaned_str)
    return None

if 'Kms Driven' in df_standardised.columns:
    df_standardised['Kms Driven'] = df_standardised['Kms Driven'].apply(clean_kms_driven)
    print("✅ Processed 'Kms Driven' column - removed non-numeric characters and converted to integer")

def convert_price_to_numeric(price_str):
    """
    Converts price strings in '₹ X.XX Lakh', '₹ X Lakh', or '₹ X.XX Crore' format to numeric INR.
    Handles potential non-numeric values by returning NaN.
    """
    if isinstance(price_str, (int, float, Decimal)):
        return float(price_str)  # Already numeric

    price_str = str(price_str).strip().replace(',', '')  # Remove leading/trailing whitespace and commas

    lakh_match = re.search(r'₹\s*(\d+(\.\d+)?)\s*Lakh', price_str, re.IGNORECASE)
    if lakh_match:
        return float(Decimal(lakh_match.group(1)) * Decimal('100000'))

    crore_match = re.search(r'₹\s*(\d+(\.\d+)?)\s*Crore', price_str, re.IGNORECASE)
    if crore_match:
        return float(Decimal(crore_match.group(1)) * Decimal('10000000'))

    # Handle cases with just numeric values (after removing '₹' and spaces)
    numeric_only = price_str.replace('₹', '').strip()
    if numeric_only.isdigit() or ('.' in numeric_only and all(c.isdigit() or c == '.' for c in numeric_only)):
        try:
            return float(numeric_only)
        except ValueError:
            return pd.NA  # Return NaN for invalid numeric strings

    return pd.NA  # Return NaN for non-convertible strings

if 'price' in df_standardised.columns:
    original_prices = df_standardised['price'].copy()
    df_standardised['price_numeric'] = df_standardised['price'].apply(convert_price_to_numeric)

    # Count NaN values after conversion
    nan_count = df_standardised['price_numeric'].isna().sum()

    # Identify non-convertible original values
    non_convertible_original = original_prices[df_standardised['price_numeric'].isna()].unique().tolist()

    # Update the original 'price' column with the numeric conversions
    df_standardised['price'] = df_standardised['price_numeric']

    print("✅ Processed 'price' column - attempted to convert 'Lakh' and 'Crore' values to numeric INR")
    print(f"Number of NaN values in 'price' column after conversion: {nan_count}")
    if non_convertible_original:
        print(f"\n⚠️ The following original values in the 'price' column could not be converted to numeric: {non_convertible_original}")
    else:
        print("\n🎉 All identified price values were successfully converted to numeric.")

    # Optionally, you can drop the temporary 'price_numeric' column
    if 'price_numeric' in df_standardised.columns:
        df_standardised.drop(columns=['price_numeric'], inplace=True)



def extract_gear_speeds_v4_modified(gear_box_str):
    """
    Extracts the number of speeds from a Gear Box string.
    Handles various formats including explicit speed numbers and common transmission types,
    assigning specific numerical values to CVT, Direct Drive, IVT, iMT, and AGS.
    Returns an integer representing the number of speeds or a specific code for other types.
    """
    if isinstance(gear_box_str, (int, float)):
        return int(gear_box_str)

    gear_box_str = str(gear_box_str).strip().lower()

    # Explicit number of speeds
    speed_match = re.search(r'(\d+)\s*speed', gear_box_str)
    if speed_match:
        return int(speed_match.group(1))

    speed_match_hyphen = re.search(r'(\d+)-speed', gear_box_str)
    if speed_match_hyphen:
        return int(speed_match_hyphen.group(1))

    # Leading number (e.g., 8G-DCT)
    leading_number_match = re.search(r'^(\d+)', gear_box_str)
    if leading_number_match:
        return int(leading_number_match.group(1))

    # Handle specific transmission types with assigned numerical values
    if 'cvt' in gear_box_str or 'ivt' in gear_box_str:
        return 0  # Or -1 to represent continuous
    elif 'direct drive' in gear_box_str:
        return 1
    elif 'imt' in gear_box_str:
        return 5  # Or 6, depending on the common range
    elif 'ags' in gear_box_str:
        return 5  # Or 6, depending on the common range

    # Handle manual transmissions (explicitly mention number of speeds)
    manual_match = re.search(r'(\d+)\s*speed\s*manual(?: transmission)?', gear_box_str)
    if manual_match:
        return int(manual_match.group(1))
    manual_match_short = re.search(r'five speed manual', gear_box_str) # Specific case
    if manual_match_short:
        return 5

    return pd.NA  # Return NaN for truly unidentifiable cases

if 'Gear Box' in df_standardised.columns:
    original_gear_box = df_standardised['Gear Box'].copy()
    df_standardised['Gear Box_numeric'] = df_standardised['Gear Box'].apply(extract_gear_speeds_v4_modified)

    # Update the original 'Gear Box' column with the numeric conversions
    df_standardised['Gear Box'] = df_standardised['Gear Box_numeric']

    print("✅ Processed 'Gear Box' column - attempted to extract the number of speeds (version 4 - modified for ML)")
    print(f"Number of NaN values in 'Gear Box' column after extraction: {df_standardised['Gear Box'].isnull().sum()}")
    if df_standardised['Gear Box'].isnull().sum() > 0:
        print(f"\n⚠️ There are still NaN values in the 'Gear Box' column for truly unidentifiable strings.")
    else:
        print("\n🎉 All 'Gear Box' values were successfully converted to a numeric representation.")

    #Optionally, you might not want to drop the temporary column for inspection
    if 'Gear Box_numeric' in df_standardised.columns:
        df_standardised.drop(columns=['Gear Box_numeric'], inplace=True)


def clean_and_transform(df_standardised):
    """Perform all cleaning and transformation operations"""
    try:
        df_transformed = df_standardised.copy()

        # ===== PROCESS KM COLUMN =====
        if 'Kms Driven' in df_standardised.columns:
            df_standardised['Kms Driven'] = clean_numeric_column(df_standardised['Kms Driven'], 'Int64')
            print("✅ Processed 'Kms Driven' column - removed commas and converted to integer")

        # ===== STANDARD TRANSFORMATIONS =====
        transformations = [
            ('owner', r'(\d+)', 'Int64'),
            ('Registration Year', r'(\d+)', 'Int64'),
            ('Seats', r'(\d+)', 'Int64'),
            ('Engine Displacement', r'(\d+)', 'Int64'),
            ('Mileage', r'(\d+\.?\d*)', float) # Extract numerical mileage
        ]

        for col, pattern, action in transformations:
            if col in df_transformed.columns:
                try:
                    if callable(action):
                        if pattern:
                            match = df_transformed[col].str.extract(pattern)
                            df_transformed[col] = match[0].apply(action) if not match.empty else None
                        else:
                            df_transformed[col] = df_transformed[col].apply(action)
                    else:
                        df_transformed[col] = clean_numeric_column(df_transformed[col], pattern, action)
                except Exception as e:
                    print(f"⚠️ Warning processing column {col}: {e}")

        return df_transformed
    except Exception as e:
        print(f"❌ Error in transformation: {e}")
        return None




df_standardised = clean_and_transform(df_standardised)

# Assuming df_standardised is your DataFrame

year_columns_to_convert = ['Year of Manufacture', 'Registration Year', 'modelYear']

for col in year_columns_to_convert:
    if col in df_standardised.columns:
        try:
            df_standardised[col] = pd.to_datetime(df_standardised[col], format='%Y').dt.to_period('Y')
            print(f"Converted '{col}' to Period[Y]")
        except ValueError:
            print(f"Could not convert '{col}' to Period[Y], keeping original type.")

print("\nDataFrame dtypes after converting year columns:")
print(df_standardised.dtypes)

print("\nDataFrame with Period[Y] dtype:")
print(df_standardised[year_columns_to_convert].head())


# Create a copy to detect data types without modifying the original
df_standardised_dtypes = df_standardised.copy().convert_dtypes()

print("Original DataFrame dtypes:")
print(df_standardised.dtypes)
print("\nDetected dtypes (without saving):")
print(df_standardised_dtypes.dtypes)
print("\nAutomatically detected the datatypes (in the copy)")


if df_standardised_dtypes is not None:
    print("\n the datatypes after transformation")
    print(df_standardised_dtypes.dtypes)
    df_standardised_dtypes.head()

    # Save the df_Standardising data
    os.makedirs("output", exist_ok=True)
    output_path = "output/banglore_standardised.csv"
    df_standardised_dtypes.to_csv(output_path, index=False)
    print(f"\n✅ Cleaned dataset saved to: {output_path}")

✅ Processed 'Kms Driven' column - removed non-numeric characters and converted to integer
✅ Processed 'price' column - attempted to convert 'Lakh' and 'Crore' values to numeric INR
Number of NaN values in 'price' column after conversion: 0

🎉 All identified price values were successfully converted to numeric.
✅ Processed 'Gear Box' column - attempted to extract the number of speeds (version 4 - modified for ML)
Number of NaN values in 'Gear Box' column after extraction: 0

🎉 All 'Gear Box' values were successfully converted to a numeric representation.
✅ Processed 'Kms Driven' column - removed commas and converted to integer
⚠️ Warning processing column Mileage: Can only use .str accessor with string values!
Converted 'Year of Manufacture' to Period[Y]
Converted 'Registration Year' to Period[Y]
Converted 'modelYear' to Period[Y]

DataFrame dtypes after converting year columns:
price                        float64
bt                            object
Kms Driven                     int64
owner                          Int64
Year of Manufacture    period[Y-DEC]
Mileage                      float64
RTO                           object
Fuel Type                     object
Registration Year      period[Y-DEC]
modelYear              period[Y-DEC]
Insurance Validity            object
Gear Box                       int64
Transmission                  object
Seats                          Int64
City                          object
Engine Displacement            Int64
dtype: object

DataFrame with Period[Y] dtype:
  Year of Manufacture Registration Year modelYear
0                2015              2015      2015
1                2018              2018      2018
2                2018              2018      2018
3                2014              2014      2014
4                2015              2015      2015
Original DataFrame dtypes:
price                        float64
bt                            object
Kms Driven                     int64
owner                          Int64
Year of Manufacture    period[Y-DEC]
Mileage                      float64
RTO                           object
Fuel Type                     object
Registration Year      period[Y-DEC]
modelYear              period[Y-DEC]
Insurance Validity            object
Gear Box                       int64
Transmission                  object
Seats                          Int64
City                          object
Engine Displacement            Int64
dtype: object

Detected dtypes (without saving):
price                           Int64
bt                     string[python]
Kms Driven                      Int64
owner                           Int64
Year of Manufacture     period[Y-DEC]
Mileage                       Float64
RTO                    string[python]
Fuel Type              string[python]
Registration Year       period[Y-DEC]
modelYear               period[Y-DEC]
Insurance Validity     string[python]
Gear Box                        Int64
Transmission           string[python]
Seats                           Int64
City                   string[python]
Engine Displacement             Int64
dtype: object

Automatically detected the datatypes (in the copy)

 the datatypes after transformation
price                           Int64
bt                     string[python]
Kms Driven                      Int64
owner                           Int64
Year of Manufacture     period[Y-DEC]
Mileage                       Float64
RTO                    string[python]
Fuel Type              string[python]
Registration Year       period[Y-DEC]
modelYear               period[Y-DEC]
Insurance Validity     string[python]
Gear Box                        Int64
Transmission           string[python]
Seats                           Int64
City                   string[python]
Engine Displacement             Int64
dtype: object

✅ Cleaned dataset saved to: output/banglore_standardised.csv

In [12]:
df_standardised_dtypes.head(10)

,price,bt,Kms Driven,owner,Year of Manufacture,Mileage,RTO,Fuel Type,Registration Year,modelYear,Insurance Validity,Gear Box,Transmission,Seats,City,Engine Displacement
0,400000,Hatchback,120000,3,2015,23.1,KA51,Petrol,2015,2015,Third Party insurance,5,Manual,5,bangalore,998
1,811000,SUV,32706,2,2018,17.0,KA05,Petrol,2018,2018,Comprehensive,5,Manual,5,bangalore,1497
2,585000,Hatchback,11949,1,2018,23.84,KA03,Petrol,2018,2018,Comprehensive,5,Manual,5,bangalore,1199
3,462000,Sedan,17794,1,2014,19.1,KA53,Petrol,2014,2014,Comprehensive,5,Manual,5,bangalore,1197
4,790000,SUV,60000,1,2015,23.65,KA04,Diesel,2015,2015,Third Party insurance,5,Manual,5,bangalore,1248
5,1900000,SUV,20000,1,2020,17.1,KA04,Diesel,2020,2020,Third Party insurance,6,Manual,5,bangalore,1956
6,345000,Hatchback,37772,1,2017,20.63,KA05,Petrol,2017,2017,Comprehensive,5,Manual,5,bangalore,1198
7,1200000,SUV,30000,1,2021,18.15,KA51,Petrol,2021,2021,Third Party insurance,7,Automatic,5,bangalore,998
8,960000,Sedan,37000,1,2018,20.28,KA03,Petrol,2018,2018,Comprehensive,4,Automatic,5,bangalore,1462
9,585000,Hatchback,11949,1,2017,23.84,KA03,Petrol,2018,2017,Comprehensive,5,Manual,5,bangalore,1199

In [13]:
nan_summary = pd.DataFrame({
    'Column': df_standardised_dtypes .columns,
    'Data Type': df_standardised_dtypes .dtypes,
    'Non-Null Count': df_standardised_dtypes.notna().sum(),
    'NaN Count': df_standardised_dtypes .isna().sum(),
    'NaN Percentage': (df_standardised_dtypes.isna().mean() * 100).round(2)
}).reset_index(drop=True)

# Display ALL rows without truncation
with pd.option_context('display.max_rows', None, 'display.width', 1000):
    print(nan_summary)

                 Column       Data Type  Non-Null Count  NaN Count  NaN Percentage
0                 price           Int64            1481          0             0.0
1                    bt  string[python]            1481          0             0.0
2            Kms Driven           Int64            1481          0             0.0
3                 owner           Int64            1481          0             0.0
4   Year of Manufacture   period[Y-DEC]            1481          0             0.0
5               Mileage         Float64            1481          0             0.0
6                   RTO  string[python]            1481          0             0.0
7             Fuel Type  string[python]            1481          0             0.0
8     Registration Year   period[Y-DEC]            1481          0             0.0
9             modelYear   period[Y-DEC]            1481          0             0.0
10   Insurance Validity  string[python]            1481          0             0.0
11             Gear Box           Int64            1481          0             0.0
12         Transmission  string[python]            1481          0             0.0
13                Seats           Int64            1481          0             0.0
14                 City  string[python]            1481          0             0.0
15  Engine Displacement           Int64            1481          0             0.0

In [ ]:
import pandas as pd
import os

# File path of the input CSV file
input_file_path = r'C:\Users\USER\Desktop\Car-Dheko_Used_Car_Price_Prediction\output\banglore_standardised.csv'

# Output directory
output_dir = r'C:\Users\USER\Desktop\Car-Dheko_Used_Car_Price_Prediction\output'
output_file_name = 'Banglore_data_format.csv'
output_file_path = os.path.join(output_dir, output_file_name)

try:
    # Read the CSV file into a Pandas DataFrame
    df = pd.read_csv(input_file_path)

    # Create a mapping dictionary for column name changes
    column_name_mapping = {
        'BODY_TYPE': 'BODY_TYPE',  # Keep as is but ensure consistent capitalization
        'Kms Driven': 'Kilometers_Driven',
        'Gear Box': 'NUMBER_OF_GEARS',
        'City': 'CITY_NAME',
        'modelYear': 'MODEL_YEAR'
    }

    # Function to format column names
    def format_column_name(col_name):
        if col_name in column_name_mapping:
            return column_name_mapping[col_name].upper()
        else:
            return col_name.upper().replace(' ', '_')

    # Apply the formatting function to all column names
    df.columns = [format_column_name(col) for col in df.columns]

    # Save the modified DataFrame to a new CSV file
    df.to_csv(output_file_path, index=False, encoding='utf-8')

    print(f"✅ Successfully formatted column names and saved to: {output_file_path}")

except FileNotFoundError:
    print(f"❌ Error: Input file not found at: {input_file_path}")
except Exception as e:
    print(f"❌ An error occurred: {e}")

***d)	Encoding Categorical Variables: Convert categorical features into numerical values using encoding techniques.***

i)	Use one-hot encoding for nominal categorical variables.

ii)	Use label encoding or ordinal encoding for ordinal categorical variables.

In [3]:
import pandas as pd


file_path=r"C:\Users\USER\Desktop\Car-Dheko_Used_Car_Price_Prediction\output\banglore_standardised.csv"
df_Banglore_1=pd.read_csv(file_path)

df_Banglore_1.head(10)

,price,bt,Kms Driven,owner,Year of Manufacture,Mileage,RTO,Fuel Type,Registration Year,modelYear,Insurance Validity,Gear Box,Transmission,Seats,City,Engine Displacement
0,400000,Hatchback,120000,3,2015,23.10,KA51,Petrol,2015,2015,Third Party insurance,5,Manual,5,bangalore,998
1,811000,SUV,32706,2,2018,17.00,KA05,Petrol,2018,2018,Comprehensive,5,Manual,5,bangalore,1497
2,585000,Hatchback,11949,1,2018,23.84,KA03,Petrol,2018,2018,Comprehensive,5,Manual,5,bangalore,1199
3,462000,Sedan,17794,1,2014,19.10,KA53,Petrol,2014,2014,Comprehensive,5,Manual,5,bangalore,1197
4,790000,SUV,60000,1,2015,23.65,KA04,Diesel,2015,2015,Third Party insurance,5,Manual,5,bangalore,1248
5,1900000,SUV,20000,1,2020,17.10,KA04,Diesel,2020,2020,Third Party insurance,6,Manual,5,bangalore,1956
6,345000,Hatchback,37772,1,2017,20.63,KA05,Petrol,2017,2017,Comprehensive,5,Manual,5,bangalore,1198
7,1200000,SUV,30000,1,2021,18.15,KA51,Petrol,2021,2021,Third Party insurance,7,Automatic,5,bangalore,998
8,960000,Sedan,37000,1,2018,20.28,KA03,Petrol,2018,2018,Comprehensive,4,Automatic,5,bangalore,1462
9,585000,Hatchback,11949,1,2017,23.84,KA03,Petrol,2018,2017,Comprehensive,5,Manual,5,bangalore,1199

Column Name | Why It's Suitable for Label Encoding
RTO | Regional codes, no meaningful order, many unique values
Insurance Validity | Can be ordinal or label encoded depending on use-case
City | Repetitive categorical field with few values
bt (Body Type) | Few categories, okay for label encoding in some models
Fuel Type | Few values, often used for ordinal, but label works too
Transmission | Manual/Automatic — 2 values, label or ordinal both work

In [20]:
#label Encoding

from sklearn.preprocessing import LabelEncoder

# Create a copy to avoid modifying the original
df_encoded_lablel_encoding = df_Banglore_1.copy()

label_cols = ['RTO', 'Insurance Validity', 'City', 'bt', 'Fuel Type', 'Transmission']

# Apply LabelEncoder to each column
le = LabelEncoder()
for col in label_cols:
    df_encoded_lablel_encoding[col] = le.fit_transform(df_encoded_lablel_encoding[col])

# Preview the result
df_encoded_lablel_encoding.head()

,price,bt,Kms Driven,owner,Year of Manufacture,Mileage,RTO,Fuel Type,Registration Year,modelYear,Insurance Validity,Gear Box,Transmission,Seats,City,Engine Displacement
0,400000,2,120000,3,2015,23.10,45,4,2015,2015,4,5,1,5,0,998
1,811000,6,32706,2,2018,17.00,15,4,2018,2018,5,5,1,5,0,1497
2,585000,2,11949,1,2018,23.84,13,4,2018,2018,5,5,1,5,0,1199
3,462000,7,17794,1,2014,19.10,47,4,2014,2014,5,5,1,5,0,1197
4,790000,6,60000,1,2015,23.65,14,1,2015,2015,4,5,1,5,0,1248

In [26]:
# check for unique values
import pandas as pd

# Assuming df_encoded_lablel_encoding is your DataFrame
if isinstance(df_encoded_lablel_encoding, pd.DataFrame):
    for column in df_encoded_lablel_encoding.columns:
        unique_values = df_encoded_lablel_encoding[column].unique()
        print(f"Unique values in column '{column}':")
        print(unique_values)
        print("-" * 30)
else:
    print("df_encoded_lablel_encoding is not a Pandas DataFrame.")

Unique values in column 'price':
[  400000   811000   585000   462000   790000  1900000   345000  1200000
   960000   690000   682000   825000   595000  1350000  5595000   521000
  1005000   775000  2200000   582000  1090000   457000  4900000   550000
   570000   220000  4145000   861000  1785000   803000  2565000   674000
   349000  1050000  4425000   406000  4965000  1100000   594000   710000
   692000   650000  2090000   411000  3675000   610000  1675000   530000
  7990000   250000   715000  3500000  2250000   625000  2695000   428000
   695000   930000   455000  1195000  2175000   442000   500000  3395000
   537000   750000  1790000   468000   420000   920000   533000   850000
   751000   388000   490000   494000   525000  2890000   365000  1895000
  5990000  2075000   394000   725000   240000   835000  1725000   330000
   990000   755000  1750000  2083000   271000  1280000   436000  1250000
  2225000   475000   600000  2450000  1625000  1650000   249000   630000
  2599000   385000   300000  2975000   276000   730000  2245000   399000
   312000  1275000  1990000   719000  1260000  3981000   627000  1300000
   672000  1825000   440000  1460000  2041000  1033000   275000   676000
  4290000   444000   510000   925000  1024000   995000   935000   834000
   560000   454000  3690000   900000  7900000   843000   799000   576000
   949000   795000  1085000  2590000   516000   777000   753000  1226000
  1150000   629000   447000   786000   745000   942000   675000   875000
   869000   425000  1070000  1025000  1000000   375000   844000   764000
   684000   320000   804000  1400000   548000   619000   865000   535000
   975000   699000   893000   941000   632000   645000  6795000   299000
  2095000  2800000   999000  1295000   329000   666000  2290000  1026000
  1700000   681000  1690000   318000   688000   265000  2000000   620000
  1470000  1475000   415000   686000   517000  3300000   499000   774000
   285000   780000   555000   607000   514000   705000   653000   872000
   564000   370000  1220000   575000   868000  3000000   980000   450000
   543000   661000   505000  2365000  6050000  1600000   520000   616000
   624000   549000   760000   524000   583000  1147000  3150000   855000
  1845000   950000   846000   424000   210000   959000   889000   836000
   660000   334000   991000  1450000   219000  1285000  4195000   729000
   432000   700000  1499000   762000  1218000  1405000  1390000  1890000
  1125000   260000   395000   405000   765000   487000  1474000  1340000
   770000   818000   724000   175000   408000   642000   390000   429000
   601000  1975000  1644000   895000   350000   581000   513000   806000
  4950000   426000   485000   351000  1495000  2750000  2345000   190000
   890000   823000   554000   815000   372000   515000   410000   685000
  5500000  1800000   180000  1950000   491000  1175000  3400000  1779000
   404000   358000  1551000   501000   617000  4700000   840000  1380000
   696000   721000   927000  3275000   905000   848000  1099000   445000
   327000   577000   679000  1445000   776000   380000  3075000   527000
   552000   459000   536000  2400000  4745000  1375000   880000  1030000
  5675000   532000   651000  3200000   740000  1699000  1765000   360000
   493000   486000   540000   407000   453000  1010000  1645000   635000
   977000  1705000   667000   636000   792000    58000   827000   382000
   512000   463000  1500000   460000   511000    55000   130000   985000
  1045000   200000   586000   584000   409000   738000   656000   483000
   185000  2100000  1245000   546000   160000   332000   809000   347000
   150000  1359000   110000   135000   170000  2850000  1449000   377000
   638000  1575000   613000  1145000   599000  2165000   120000   165000
   888000   707000   593000   574000   573000    70000   430000  1075000
   615000   746000   634000    40000   579000   965000  3600000   982000
   810000   383000   605000  1345000   734000   701000   789000   477000
  1525000   562000   670000    80000   531000   558000   155000   508000
  2060000   542000  1370000  3250000  2475000   417000   631000   465000
   544000   704000   359000   335000   766000   480000   822000  3795000
   539000  1006000  3900000   796000   718000   280000   559000   268000
   864000   341000   800000  3750000   338000   604000 13000000   621000
   140000   708000   443000   470000  1850000    75000   649000   657000
   322000   435000   317000   830000    65000   547000   413000  2325000
   709000  2295000   528000   691000  2550000   609000   678000   449000
    56000   845000   680000   720000    60000   357000   798000   858000
   608000   698000  1035000   328000    76000   232000   966000   781000
   749000  2350000   230000   898000  2395000  1485000  3825000  2500000
  1540000  1290000    50000   808000   278000  1261000   270000   340000
  1225000  2900000   315000  1328000  1724000   225000   100000  1329000
  1358000   911000  1565000   479000   736000  2600000  4445000   618000
   916000   125000   590000   381000   819000   195000  1013000   677000
   591000   697000   464000  1695000  2700000   733000  1885000  1193000
  2150000  1585000  7000000   689000  1068000  1799000   639000   325000
   290000  1774000  1073000   658000   495000   647000   245000   659000
   867000   389000   186000   694000   384000   782000   663000   316000
  1595000  1057000  1264000  1666000  3875000  3775000  2198000   612000
  3299000   643000   838000  2545000   655000   476000  1299000   492000
  1365000  1488000   939000  1944000   551000   352000  1519000   737000
   526000  3194000  1899000  1545000  3495000   626000  1775000  2875000
  2275000  1550000  3025000  4275000  4450000  1007000   906000  1031000
  1395000  1423000  4399000   747000  1590000   403000  1440000  5275000
  3800000   507000  1020000   472000   471000   821000   402000  1002000
  1298000  1109000   466000   924000   378000   899000   945000  1605000
  1170000  9500000  2195000   421000  1349000  4100000  2190000   446000
  1018000   654000   310000  1084000  1382000  3575000   962000   849000
  5750000   306000   348000  2425000   541000   568000   637000  1649000]
------------------------------
Unique values in column 'bt':
[2 6 7 3 1 4 5 0]
------------------------------
Unique values in column 'Kms Driven':
[120000  32706  11949  17794  60000  20000  37772  30000  37000  50000
  24887  23000  48928 108862  80000  16000  65376  10000  67000 100000
  18083  57634 110000  23447  33000  87667  40000  79012  31344  12434
  12000  40987  18157  89667  56997  59000  18835  60932  33539  66837
    400  44285  25000  36735  79000  53645  53982  37741  17367  94000
  33700  54601  64000  40525  44154  70000  68039  49873  90000  48960
  68000  23017  83000  92000  62139  74000  26500  81716  24000  18000
  38197  19000  14000  29268  64374   7100  43679  40562  58600  42050
  65017  36349  83394  52204  89000  29813  13345  17100  75000  75523
  47000  36500  28253  52571  61993  57000  36359   7500  30301  66000
  56010  83829  35000  51116  85565  36916 112795  11000  36685   4000
  32184  32279  59698  46071   9554  74499  56211   9001  65457  23682
 134557  96567  83007  34000  81634  57284  46429  17624  49690  55702
  45046  53000  94695  22162 115331  42233  20941  46602 104000  50035
  25170  25022  26367  76567  36459  93725 115599  43469  77000  72000
  87101  40771  28000  26000  76032 113780  65812  39959  65484  49174
  63797  60216  38153  76485  40623  88051  16522  35469  40073  65730
  36184  69310  55643  62803  68656  77501  48325  69000  14999  90773
  64917  70235  78782 164000  72136  52486 150000  36887  47962 135000
  47398  55000 116624  54561  65072 133532  39886  56976  68303  54000
  98500  72348  62696 174000  65000  36000 199000  71905  69748  44000
  17875  95678  12003 114427  64655  46456  27000  91598  57521   7598
  38520 110455  26901  28177  82998  14500  25887  74094  91045  80033
  13957  34140  20056  38233  98000  16998  15256   4495  34561 142135
   9553   7600  45578  42000  16306  25086  54845  35642  22173  67790
  38000  49713  10002  46706 106000  55833  46716 113348 134000  52311
  59514  36743  83046  59420   4545  70404  39725  23272   8407  14881
  54305  64998  75940  25639  44107  41594  24786  56000  31000  19065
  30538  48891  26676  35647  63825  31346  79349  88203  37370  52228
  40542  47936  45000  20469  46258  54242  90727  31003  24233  36983
  68915   5440   8096 125903  33040  30722  58778  51395  65881  49934
  91000  61576 114321  53125  36462  97542  13000  41000  94471  58000
  46000  36531  36004  58808  31983  78536  54134  27227  25508  19047
  64453  43387  36538  36787  32112  53701  26085  46894  53692  37809
  30813  56254  15727    150  21113  71775  59882  24463  72352  90928
 117530 102814  34801  51877  17125  50318  46123  33360  21800  11045
  51406  26031  30740  65909 140590  32953  51801  62621  79068  36314
  21236  47488  56814  63206  61103 112268  97346  36977  85700  40082
 112566  61978  27658  43371  67633  76794  59577  94932  75140  88000
  73969  62598  24343  58917  72338  64235  83873  93059  45681  45938
  57423  60942  19875  14949  77995  40908  39693  63411  94221  93975
  30155  59006  18570  48246  61263  65507  26158  35250  65965  40304
  56661  90213  20739  47127  47038  40769  34757  88119  57176  62223
  52000  63251  67444  63837  61000  60777  39248  96198  81207  48148
  64389  67245  30518 102407  53606  44253  34702  42762  57459  70381
  80648  81853  90802  16502  31530  71086  69210  71165  86543  67225
  16247  39481  61227 112521  63359 125227  71884  79059  69124  73340
  44268  37354  80426  89801  69199  78249  26918  29905  37678  60442
  66463  40844  79415  88411 106516  88509  44437  83731  45621  38199
  91660  51947  76836  33222  47333  43791  87660  71938 104938 124707
  88556  48743  51338  97334  53031  51580  23920  66434  54097  27655
  14955  14338  73799  39139  89633  16826  25133  34990  33210  28051
  22280  21193   7150  13262  21000  61902  38396   7561   6731  55567
  48938  71545  56577  56974  40344  36216  45965  74982  21925  50406
  26483  12104  23721   8212   9358  62011  38771  42174  43199  10155
 110654  50704  34725  57709  26224  32196  56672  21226 105000  10346
  16679  15437  15017  75283  54568  14516  53627   5083  50666  16962
  70446  60528   7132  21280  82021  18998  56189  57644  51286  27937
  40031  47619  30535  20229  35800  11453  35410  49948  48285  19062
  87000  56276  27103  46507  39070  22438  21225  28737  90106 138175
  55609  56410  77593  49538  41268  60020  32148  69565  26007 134850
  44385 102662  13802  13444  56226   8733  57963  19508  49423  78622
  18025  68220   6000  59889  38500  39157 162000  89900  58666  54137
 180000  21997  40394  49000  80390  52721  55127  35922  16883  86000
  55398  25829  36913  42162  48041  43285  44326  62984  99276  42812
  57770  42220  66977  29916  10066  39243  36309  69408  12064  17190
  58323  40765  58198  42976 104507  44074  14089  94378  71000 113000
 170402  25883  32746  35038  38995  61102 132000  52288  69054  51745
  22000  11268  24357 157000   9982  39613  68906  71423  17811   9724
  20754  50510  85000  48979   9000  78000   1500   8187  81777  48698
  67771  60386 111374  40561  92529  55342  51000  36468  11250  36368
  62000  39466  49570  23382  42954  68306  54961  91087  16691  80190
  54639  50225  68017  87912   2045  24305   2500  31489  82268  73834
  73000  41436  19024  73140  29289  39116  41958  26626  63460  35711
  20057  25396  35993  74280  82000  63773 101356  75591  72208  51489
  74643  79575  35288  70314  96939  44824 169219  92673  20183  77130
  27025 105153  70509  11662  36176  74342  89837  11912  55544  27027
  56363  42094 114912  33649  69798  49001  57527  57367  50936  23237
  66596  36613  74104   6777  14560  90333  50114  69301  71306  35135
 102000  41659  85300  32483  34376  36540 148625  81000   5609  30285
  80153  49641  83075  45677  81849  67791  38100  65015  62029  94926
 119487 126000  70332  37950 156039  93003]
------------------------------
Unique values in column 'owner':
[3 2 1 4 5]
------------------------------
Unique values in column 'Year of Manufacture':
[2015 2018 2014 2020 2017 2021 2019 2022 2016 2011 2009 2013 2010 2008
 2006 2012 2005 2007 2023 2004 2003 2002]
------------------------------
Unique values in column 'Mileage':
[ 23.1   17.    23.84  19.1   23.65  17.1   20.63  18.15  20.28  21.4
  18.9   18.2   15.1   21.27  17.33  17.8   18.48  22.38  16.42   7.81
  17.4   20.3   13.45  15.    17.11  20.14  20.51  19.34  12.6   15.56
  11.5   19.87  18.6   22.54  16.3   18.53  22.05  12.05  16.5   19.7
  11.3   14.08  12.07  22.    21.5   15.3   26.68  21.14  15.9   19.67
  14.6   28.4   21.76  26.21  19.    19.98  18.5   20.    16.8   17.2
  21.13  24.    25.32  16.55  19.2   24.04  27.03  16.56  19.4   19.56
  20.92  19.03  21.1   18.19  17.41  14.2   19.81  14.8   16.    18.4
  13.2   14.1   20.36  13.24  14.16  24.39  10.91  18.16  20.89  18.1
  16.35  15.97  16.07  16.38  14.24  17.9   19.01  25.2   19.6   18.
  17.21  11.1   11.4   11.72  13.32  20.37  24.3   18.27  20.45  18.7
  22.41  20.77  15.63  20.54  21.19  27.39  17.92  26.    10.    17.5
  11.18  23.    17.57  14.21  21.43  20.65  22.9   14.5   12.99  19.12
  13.8   13.38  14.7   16.36  18.24  21.56  20.38  23.7   20.08  10.9
  21.21  15.43  21.74  23.95  19.27  15.4   22.07  20.85  17.01  14.11
  22.56  20.5   20.4   20.73  15.6   14.67  19.3   14.71  17.69  13.6
  21.72  12.51  16.2   13.    17.74  12.55  12.8   22.35  22.77  25.24
  17.7   13.06  12.3   17.14  21.03  21.7   23.2   14.69  22.5   20.52
  21.46  22.69  22.32  21.01  24.4   17.42  18.56  15.73  17.68  16.13
  13.79  18.25  18.3   15.5   15.17  14.99  11.9   15.29  16.09  16.47
  20.09  21.63  15.26  11.57  17.03  20.8   17.19  12.    23.9   20.04
 110.    14.59  14.    18.45  16.96  12.65  19.33  19.65  22.15  25.
  14.82  10.75  21.73   8.    16.1   20.68  22.7   11.36  13.4   18.49
  14.28  17.88  16.11  20.7   16.82  17.3   20.46  12.35  15.04  18.75
  15.2   18.12  18.06  11.7   20.1   22.74  28.09  17.67  20.88  26.11
  22.1   13.5   24.52  20.25  13.58  10.54  15.7   19.64 140.    13.68
  16.24  26.59  13.7   17.6   19.69  15.41  14.9   17.52  17.05  24.7
  21.9   25.4   19.47  21.66  25.8   10.5   14.4    9.    19.09  23.01
  22.25  27.28  21.64  22.61  15.8   18.09  19.28  18.78  11.74   8.9
  15.85  18.76  16.95  23.59  14.84  19.5   21.    15.96  27.3   18.88
  13.93  14.74  16.4   16.28  20.86  18.07  21.79  16.6   13.9   26.1
  13.92  18.55  14.02  31.59  19.72  14.57  21.8 ]
------------------------------
Unique values in column 'RTO':
[45 15 13 47 14 11 63 40 12  8 79 43 26 44 18 64 51 27 46 30 32 66 21 60
 41 20 53 48 17 24 23 69 16 29 22 37 28 34 54 50 31 19 38 39 25  4 73 36
 42  1  5 61 68 57 67 78 76 59 56 77 75 72 55 62 49 52 33 71  6 74  3  0
  9 65  7  2 58 10 35 70]
------------------------------
Unique values in column 'Fuel Type':
[4 1 3 0 2]
------------------------------
Unique values in column 'Registration Year':
[2015 2018 2014 2020 2017 2021 2019 2022 2016 2011 2009 2013 2010 2008
 2006 2012 2005 2007 2023 2004 2003 2002]
------------------------------
Unique values in column 'modelYear':
[2015 2018 2014 2020 2017 2021 2019 2022 2016 2011 2009 2013 2010 2008
 2006 2012 2005 2007 2023 1995 1998 2004 2003 2001 2002 2000]
------------------------------
Unique values in column 'Insurance Validity':
['4' '5' '3' '6' '2' '1' '0']
------------------------------
Unique values in column 'Gear Box':
[5 6 7 4 8 9 0 1]
------------------------------
Unique values in column 'Transmission':
[1 0]
------------------------------
Unique values in column 'Seats':
[ 5  7  4  6  8 10  9]
------------------------------
Unique values in column 'City':
[0]
------------------------------
Unique values in column 'Engine Displacement':
[ 998 1497 1199 1197 1248 1956 1198 1462 2179 1950 1396 1995 1498 4663
 1086 1991 1968 1998 2982 1461 1797  796 1353 2925 2987 2967  999 1341
 1496 1582 1798 1120 1969 1451  814 1999 1591 1397 1368 1598 3198 1196
 2993 2755 2143 2354 1332 2199 1997 1499 2148 2696 1364 2494 1373 1299
 1061 1493 2497 1495 1590 1896 1330 1781 1390 1194 2953 1399 1595 2496
    0 1984 2694 1298 2362  970 2198 1599  993 2393 1389 1597 2498 2523
 1586  995 2499 2998   72 1589  624 1596  799 3597 2184 1405 5000 1422
 1047 2200 2996 1108 2400 1996 1395]
------------------------------

In [20]:
df_Banglore_1.price.unique()

array([  400000,   811000,   585000,   462000,   790000,  1900000,
         345000,  1200000,   960000,   690000,   682000,   825000,
         595000,  1350000,  5595000,   521000,  1005000,   775000,
        2200000,   582000,  1090000,   457000,  4900000,   550000,
         570000,   220000,  4145000,   861000,  1785000,   803000,
        2565000,   674000,   349000,  1050000,  4425000,   406000,
        4965000,  1100000,   594000,   710000,   692000,   650000,
        2090000,   411000,  3675000,   610000,  1675000,   530000,
        7990000,   250000,   715000,  3500000,  2250000,   625000,
        2695000,   428000,   695000,   930000,   455000,  1195000,
        2175000,   442000,   500000,  3395000,   537000,   750000,
        1790000,   468000,   420000,   920000,   533000,   850000,
         751000,   388000,   490000,   494000,   525000,  2890000,
         365000,  1895000,  5990000,  2075000,   394000,   725000,
         240000,   835000,  1725000,   330000,   990000,   755000,
        1750000,  2083000,   271000,  1280000,   436000,  1250000,
        2225000,   475000,   600000,  2450000,  1625000,  1650000,
         249000,   630000,  2599000,   385000,   300000,  2975000,
         276000,   730000,  2245000,   399000,   312000,  1275000,
        1990000,   719000,  1260000,  3981000,   627000,  1300000,
         672000,  1825000,   440000,  1460000,  2041000,  1033000,
         275000,   676000,  4290000,   444000,   510000,   925000,
        1024000,   995000,   935000,   834000,   560000,   454000,
        3690000,   900000,  7900000,   843000,   799000,   576000,
         949000,   795000,  1085000,  2590000,   516000,   777000,
         753000,  1226000,  1150000,   629000,   447000,   786000,
         745000,   942000,   675000,   875000,   869000,   425000,
        1070000,  1025000,  1000000,   375000,   844000,   764000,
         684000,   320000,   804000,  1400000,   548000,   619000,
         865000,   535000,   975000,   699000,   893000,   941000,
         632000,   645000,  6795000,   299000,  2095000,  2800000,
         999000,  1295000,   329000,   666000,  2290000,  1026000,
        1700000,   681000,  1690000,   318000,   688000,   265000,
        2000000,   620000,  1470000,  1475000,   415000,   686000,
         517000,  3300000,   499000,   774000,   285000,   780000,
         555000,   607000,   514000,   705000,   653000,   872000,
         564000,   370000,  1220000,   575000,   868000,  3000000,
         980000,   450000,   543000,   661000,   505000,  2365000,
        6050000,  1600000,   520000,   616000,   624000,   549000,
         760000,   524000,   583000,  1147000,  3150000,   855000,
        1845000,   950000,   846000,   424000,   210000,   959000,
         889000,   836000,   660000,   334000,   991000,  1450000,
         219000,  1285000,  4195000,   729000,   432000,   700000,
        1499000,   762000,  1218000,  1405000,  1390000,  1890000,
        1125000,   260000,   395000,   405000,   765000,   487000,
        1474000,  1340000,   770000,   818000,   724000,   175000,
         408000,   642000,   390000,   429000,   601000,  1975000,
        1644000,   895000,   350000,   581000,   513000,   806000,
        4950000,   426000,   485000,   351000,  1495000,  2750000,
        2345000,   190000,   890000,   823000,   554000,   815000,
         372000,   515000,   410000,   685000,  5500000,  1800000,
         180000,  1950000,   491000,  1175000,  3400000,  1779000,
         404000,   358000,  1551000,   501000,   617000,  4700000,
         840000,  1380000,   696000,   721000,   927000,  3275000,
         905000,   848000,  1099000,   445000,   327000,   577000,
         679000,  1445000,   776000,   380000,  3075000,   527000,
         552000,   459000,   536000,  2400000,  4745000,  1375000,
         880000,  1030000,  5675000,   532000,   651000,  3200000,
         740000,  1699000,  1765000,   360000,   493000,   486000,
         540000,   407000,   453000,  1010000,  1645000,   635000,
         977000,  1705000,   667000,   636000,   792000,    58000,
         827000,   382000,   512000,   463000,  1500000,   460000,
         511000,    55000,   130000,   985000,  1045000,   200000,
         586000,   584000,   409000,   738000,   656000,   483000,
         185000,  2100000,  1245000,   546000,   160000,   332000,
         809000,   347000,   150000,  1359000,   110000,   135000,
         170000,  2850000,  1449000,   377000,   638000,  1575000,
         613000,  1145000,   599000,  2165000,   120000,   165000,
         888000,   707000,   593000,   574000,   573000,    70000,
         430000,  1075000,   615000,   746000,   634000,    40000,
         579000,   965000,  3600000,   982000,   810000,   383000,
         605000,  1345000,   734000,   701000,   789000,   477000,
        1525000,   562000,   670000,    80000,   531000,   558000,
         155000,   508000,  2060000,   542000,  1370000,  3250000,
        2475000,   417000,   631000,   465000,   544000,   704000,
         359000,   335000,   766000,   480000,   822000,  3795000,
         539000,  1006000,  3900000,   796000,   718000,   280000,
         559000,   268000,   864000,   341000,   800000,  3750000,
         338000,   604000, 13000000,   621000,   140000,   708000,
         443000,   470000,  1850000,    75000,   649000,   657000,
         322000,   435000,   317000,   830000,    65000,   547000,
         413000,  2325000,   709000,  2295000,   528000,   691000,
        2550000,   609000,   678000,   449000,    56000,   845000,
         680000,   720000,    60000,   357000,   798000,   858000,
         608000,   698000,  1035000,   328000,    76000,   232000,
         966000,   781000,   749000,  2350000,   230000,   898000,
        2395000,  1485000,  3825000,  2500000,  1540000,  1290000,
          50000,   808000,   278000,  1261000,   270000,   340000,
        1225000,  2900000,   315000,  1328000,  1724000,   225000,
         100000,  1329000,  1358000,   911000,  1565000,   479000,
         736000,  2600000,  4445000,   618000,   916000,   125000,
         590000,   381000,   819000,   195000,  1013000,   677000,
         591000,   697000,   464000,  1695000,  2700000,   733000,
        1885000,  1193000,  2150000,  1585000,  7000000,   689000,
        1068000,  1799000,   639000,   325000,   290000,  1774000,
        1073000,   658000,   495000,   647000,   245000,   659000,
         867000,   389000,   186000,   694000,   384000,   782000,
         663000,   316000,  1595000,  1057000,  1264000,  1666000,
        3875000,  3775000,  2198000,   612000,  3299000,   643000,
         838000,  2545000,   655000,   476000,  1299000,   492000,
        1365000,  1488000,   939000,  1944000,   551000,   352000,
        1519000,   737000,   526000,  3194000,  1899000,  1545000,
        3495000,   626000,  1775000,  2875000,  2275000,  1550000,
        3025000,  4275000,  4450000,  1007000,   906000,  1031000,
        1395000,  1423000,  4399000,   747000,  1590000,   403000,
        1440000,  5275000,  3800000,   507000,  1020000,   472000,
         471000,   821000,   402000,  1002000,  1298000,  1109000,
         466000,   924000,   378000,   899000,   945000,  1605000,
        1170000,  9500000,  2195000,   421000,  1349000,  4100000,
        2190000,   446000,  1018000,   654000,   310000,  1084000,
        1382000,  3575000,   962000,   849000,  5750000,   306000,
         348000,  2425000,   541000,   568000,   637000,  1649000])

In [24]:
df_Banglore_1.owner.unique()

array([3, 2, 1, 4, 5])

Ordinal Encoding

Column | Ordinal Encoding? | Why?
Insurance Validity | ✅ Yes (again) | Has natural order: 'Third Party insurance' < 'Comprehensive'
owner | ✅ Yes | Represents ownership count: 1st owner < 2nd owner < 3rd...
Gear Box | ✅ Yes | Typically higher number = more gears (ordered technically)
Seats | ✅ Yes (Optional) | More seats = larger vehicles — can be ordinal in some contexts

In [21]:

# check for unique values
import pandas as pd

# Assuming df_encoded_lablel_encoding is your DataFrame
if isinstance(df_encoded_lablel_encoding, pd.DataFrame):
    for column in df_encoded_lablel_encoding.columns:
        unique_values = df_encoded_lablel_encoding[column].unique()
        print(f"Unique values in column '{column}':")
        print(unique_values)
        print("-" * 30)
else:
    print("df_encoded_lablel_encoding is not a Pandas DataFrame.")

Unique values in column 'price':
[  400000   811000   585000   462000   790000  1900000   345000  1200000
   960000   690000   682000   825000   595000  1350000  5595000   521000
  1005000   775000  2200000   582000  1090000   457000  4900000   550000
   570000   220000  4145000   861000  1785000   803000  2565000   674000
   349000  1050000  4425000   406000  4965000  1100000   594000   710000
   692000   650000  2090000   411000  3675000   610000  1675000   530000
  7990000   250000   715000  3500000  2250000   625000  2695000   428000
   695000   930000   455000  1195000  2175000   442000   500000  3395000
   537000   750000  1790000   468000   420000   920000   533000   850000
   751000   388000   490000   494000   525000  2890000   365000  1895000
  5990000  2075000   394000   725000   240000   835000  1725000   330000
   990000   755000  1750000  2083000   271000  1280000   436000  1250000
  2225000   475000   600000  2450000  1625000  1650000   249000   630000
  2599000   385000   300000  2975000   276000   730000  2245000   399000
   312000  1275000  1990000   719000  1260000  3981000   627000  1300000
   672000  1825000   440000  1460000  2041000  1033000   275000   676000
  4290000   444000   510000   925000  1024000   995000   935000   834000
   560000   454000  3690000   900000  7900000   843000   799000   576000
   949000   795000  1085000  2590000   516000   777000   753000  1226000
  1150000   629000   447000   786000   745000   942000   675000   875000
   869000   425000  1070000  1025000  1000000   375000   844000   764000
   684000   320000   804000  1400000   548000   619000   865000   535000
   975000   699000   893000   941000   632000   645000  6795000   299000
  2095000  2800000   999000  1295000   329000   666000  2290000  1026000
  1700000   681000  1690000   318000   688000   265000  2000000   620000
  1470000  1475000   415000   686000   517000  3300000   499000   774000
   285000   780000   555000   607000   514000   705000   653000   872000
   564000   370000  1220000   575000   868000  3000000   980000   450000
   543000   661000   505000  2365000  6050000  1600000   520000   616000
   624000   549000   760000   524000   583000  1147000  3150000   855000
  1845000   950000   846000   424000   210000   959000   889000   836000
   660000   334000   991000  1450000   219000  1285000  4195000   729000
   432000   700000  1499000   762000  1218000  1405000  1390000  1890000
  1125000   260000   395000   405000   765000   487000  1474000  1340000
   770000   818000   724000   175000   408000   642000   390000   429000
   601000  1975000  1644000   895000   350000   581000   513000   806000
  4950000   426000   485000   351000  1495000  2750000  2345000   190000
   890000   823000   554000   815000   372000   515000   410000   685000
  5500000  1800000   180000  1950000   491000  1175000  3400000  1779000
   404000   358000  1551000   501000   617000  4700000   840000  1380000
   696000   721000   927000  3275000   905000   848000  1099000   445000
   327000   577000   679000  1445000   776000   380000  3075000   527000
   552000   459000   536000  2400000  4745000  1375000   880000  1030000
  5675000   532000   651000  3200000   740000  1699000  1765000   360000
   493000   486000   540000   407000   453000  1010000  1645000   635000
   977000  1705000   667000   636000   792000    58000   827000   382000
   512000   463000  1500000   460000   511000    55000   130000   985000
  1045000   200000   586000   584000   409000   738000   656000   483000
   185000  2100000  1245000   546000   160000   332000   809000   347000
   150000  1359000   110000   135000   170000  2850000  1449000   377000
   638000  1575000   613000  1145000   599000  2165000   120000   165000
   888000   707000   593000   574000   573000    70000   430000  1075000
   615000   746000   634000    40000   579000   965000  3600000   982000
   810000   383000   605000  1345000   734000   701000   789000   477000
  1525000   562000   670000    80000   531000   558000   155000   508000
  2060000   542000  1370000  3250000  2475000   417000   631000   465000
   544000   704000   359000   335000   766000   480000   822000  3795000
   539000  1006000  3900000   796000   718000   280000   559000   268000
   864000   341000   800000  3750000   338000   604000 13000000   621000
   140000   708000   443000   470000  1850000    75000   649000   657000
   322000   435000   317000   830000    65000   547000   413000  2325000
   709000  2295000   528000   691000  2550000   609000   678000   449000
    56000   845000   680000   720000    60000   357000   798000   858000
   608000   698000  1035000   328000    76000   232000   966000   781000
   749000  2350000   230000   898000  2395000  1485000  3825000  2500000
  1540000  1290000    50000   808000   278000  1261000   270000   340000
  1225000  2900000   315000  1328000  1724000   225000   100000  1329000
  1358000   911000  1565000   479000   736000  2600000  4445000   618000
   916000   125000   590000   381000   819000   195000  1013000   677000
   591000   697000   464000  1695000  2700000   733000  1885000  1193000
  2150000  1585000  7000000   689000  1068000  1799000   639000   325000
   290000  1774000  1073000   658000   495000   647000   245000   659000
   867000   389000   186000   694000   384000   782000   663000   316000
  1595000  1057000  1264000  1666000  3875000  3775000  2198000   612000
  3299000   643000   838000  2545000   655000   476000  1299000   492000
  1365000  1488000   939000  1944000   551000   352000  1519000   737000
   526000  3194000  1899000  1545000  3495000   626000  1775000  2875000
  2275000  1550000  3025000  4275000  4450000  1007000   906000  1031000
  1395000  1423000  4399000   747000  1590000   403000  1440000  5275000
  3800000   507000  1020000   472000   471000   821000   402000  1002000
  1298000  1109000   466000   924000   378000   899000   945000  1605000
  1170000  9500000  2195000   421000  1349000  4100000  2190000   446000
  1018000   654000   310000  1084000  1382000  3575000   962000   849000
  5750000   306000   348000  2425000   541000   568000   637000  1649000]
------------------------------
Unique values in column 'bt':
[2 6 7 3 1 4 5 0]
------------------------------
Unique values in column 'Kms Driven':
[120000  32706  11949  17794  60000  20000  37772  30000  37000  50000
  24887  23000  48928 108862  80000  16000  65376  10000  67000 100000
  18083  57634 110000  23447  33000  87667  40000  79012  31344  12434
  12000  40987  18157  89667  56997  59000  18835  60932  33539  66837
    400  44285  25000  36735  79000  53645  53982  37741  17367  94000
  33700  54601  64000  40525  44154  70000  68039  49873  90000  48960
  68000  23017  83000  92000  62139  74000  26500  81716  24000  18000
  38197  19000  14000  29268  64374   7100  43679  40562  58600  42050
  65017  36349  83394  52204  89000  29813  13345  17100  75000  75523
  47000  36500  28253  52571  61993  57000  36359   7500  30301  66000
  56010  83829  35000  51116  85565  36916 112795  11000  36685   4000
  32184  32279  59698  46071   9554  74499  56211   9001  65457  23682
 134557  96567  83007  34000  81634  57284  46429  17624  49690  55702
  45046  53000  94695  22162 115331  42233  20941  46602 104000  50035
  25170  25022  26367  76567  36459  93725 115599  43469  77000  72000
  87101  40771  28000  26000  76032 113780  65812  39959  65484  49174
  63797  60216  38153  76485  40623  88051  16522  35469  40073  65730
  36184  69310  55643  62803  68656  77501  48325  69000  14999  90773
  64917  70235  78782 164000  72136  52486 150000  36887  47962 135000
  47398  55000 116624  54561  65072 133532  39886  56976  68303  54000
  98500  72348  62696 174000  65000  36000 199000  71905  69748  44000
  17875  95678  12003 114427  64655  46456  27000  91598  57521   7598
  38520 110455  26901  28177  82998  14500  25887  74094  91045  80033
  13957  34140  20056  38233  98000  16998  15256   4495  34561 142135
   9553   7600  45578  42000  16306  25086  54845  35642  22173  67790
  38000  49713  10002  46706 106000  55833  46716 113348 134000  52311
  59514  36743  83046  59420   4545  70404  39725  23272   8407  14881
  54305  64998  75940  25639  44107  41594  24786  56000  31000  19065
  30538  48891  26676  35647  63825  31346  79349  88203  37370  52228
  40542  47936  45000  20469  46258  54242  90727  31003  24233  36983
  68915   5440   8096 125903  33040  30722  58778  51395  65881  49934
  91000  61576 114321  53125  36462  97542  13000  41000  94471  58000
  46000  36531  36004  58808  31983  78536  54134  27227  25508  19047
  64453  43387  36538  36787  32112  53701  26085  46894  53692  37809
  30813  56254  15727    150  21113  71775  59882  24463  72352  90928
 117530 102814  34801  51877  17125  50318  46123  33360  21800  11045
  51406  26031  30740  65909 140590  32953  51801  62621  79068  36314
  21236  47488  56814  63206  61103 112268  97346  36977  85700  40082
 112566  61978  27658  43371  67633  76794  59577  94932  75140  88000
  73969  62598  24343  58917  72338  64235  83873  93059  45681  45938
  57423  60942  19875  14949  77995  40908  39693  63411  94221  93975
  30155  59006  18570  48246  61263  65507  26158  35250  65965  40304
  56661  90213  20739  47127  47038  40769  34757  88119  57176  62223
  52000  63251  67444  63837  61000  60777  39248  96198  81207  48148
  64389  67245  30518 102407  53606  44253  34702  42762  57459  70381
  80648  81853  90802  16502  31530  71086  69210  71165  86543  67225
  16247  39481  61227 112521  63359 125227  71884  79059  69124  73340
  44268  37354  80426  89801  69199  78249  26918  29905  37678  60442
  66463  40844  79415  88411 106516  88509  44437  83731  45621  38199
  91660  51947  76836  33222  47333  43791  87660  71938 104938 124707
  88556  48743  51338  97334  53031  51580  23920  66434  54097  27655
  14955  14338  73799  39139  89633  16826  25133  34990  33210  28051
  22280  21193   7150  13262  21000  61902  38396   7561   6731  55567
  48938  71545  56577  56974  40344  36216  45965  74982  21925  50406
  26483  12104  23721   8212   9358  62011  38771  42174  43199  10155
 110654  50704  34725  57709  26224  32196  56672  21226 105000  10346
  16679  15437  15017  75283  54568  14516  53627   5083  50666  16962
  70446  60528   7132  21280  82021  18998  56189  57644  51286  27937
  40031  47619  30535  20229  35800  11453  35410  49948  48285  19062
  87000  56276  27103  46507  39070  22438  21225  28737  90106 138175
  55609  56410  77593  49538  41268  60020  32148  69565  26007 134850
  44385 102662  13802  13444  56226   8733  57963  19508  49423  78622
  18025  68220   6000  59889  38500  39157 162000  89900  58666  54137
 180000  21997  40394  49000  80390  52721  55127  35922  16883  86000
  55398  25829  36913  42162  48041  43285  44326  62984  99276  42812
  57770  42220  66977  29916  10066  39243  36309  69408  12064  17190
  58323  40765  58198  42976 104507  44074  14089  94378  71000 113000
 170402  25883  32746  35038  38995  61102 132000  52288  69054  51745
  22000  11268  24357 157000   9982  39613  68906  71423  17811   9724
  20754  50510  85000  48979   9000  78000   1500   8187  81777  48698
  67771  60386 111374  40561  92529  55342  51000  36468  11250  36368
  62000  39466  49570  23382  42954  68306  54961  91087  16691  80190
  54639  50225  68017  87912   2045  24305   2500  31489  82268  73834
  73000  41436  19024  73140  29289  39116  41958  26626  63460  35711
  20057  25396  35993  74280  82000  63773 101356  75591  72208  51489
  74643  79575  35288  70314  96939  44824 169219  92673  20183  77130
  27025 105153  70509  11662  36176  74342  89837  11912  55544  27027
  56363  42094 114912  33649  69798  49001  57527  57367  50936  23237
  66596  36613  74104   6777  14560  90333  50114  69301  71306  35135
 102000  41659  85300  32483  34376  36540 148625  81000   5609  30285
  80153  49641  83075  45677  81849  67791  38100  65015  62029  94926
 119487 126000  70332  37950 156039  93003]
------------------------------
Unique values in column 'owner':
[3 2 1 4 5]
------------------------------
Unique values in column 'Year of Manufacture':
[2015 2018 2014 2020 2017 2021 2019 2022 2016 2011 2009 2013 2010 2008
 2006 2012 2005 2007 2023 2004 2003 2002]
------------------------------
Unique values in column 'Mileage':
[ 23.1   17.    23.84  19.1   23.65  17.1   20.63  18.15  20.28  21.4
  18.9   18.2   15.1   21.27  17.33  17.8   18.48  22.38  16.42   7.81
  17.4   20.3   13.45  15.    17.11  20.14  20.51  19.34  12.6   15.56
  11.5   19.87  18.6   22.54  16.3   18.53  22.05  12.05  16.5   19.7
  11.3   14.08  12.07  22.    21.5   15.3   26.68  21.14  15.9   19.67
  14.6   28.4   21.76  26.21  19.    19.98  18.5   20.    16.8   17.2
  21.13  24.    25.32  16.55  19.2   24.04  27.03  16.56  19.4   19.56
  20.92  19.03  21.1   18.19  17.41  14.2   19.81  14.8   16.    18.4
  13.2   14.1   20.36  13.24  14.16  24.39  10.91  18.16  20.89  18.1
  16.35  15.97  16.07  16.38  14.24  17.9   19.01  25.2   19.6   18.
  17.21  11.1   11.4   11.72  13.32  20.37  24.3   18.27  20.45  18.7
  22.41  20.77  15.63  20.54  21.19  27.39  17.92  26.    10.    17.5
  11.18  23.    17.57  14.21  21.43  20.65  22.9   14.5   12.99  19.12
  13.8   13.38  14.7   16.36  18.24  21.56  20.38  23.7   20.08  10.9
  21.21  15.43  21.74  23.95  19.27  15.4   22.07  20.85  17.01  14.11
  22.56  20.5   20.4   20.73  15.6   14.67  19.3   14.71  17.69  13.6
  21.72  12.51  16.2   13.    17.74  12.55  12.8   22.35  22.77  25.24
  17.7   13.06  12.3   17.14  21.03  21.7   23.2   14.69  22.5   20.52
  21.46  22.69  22.32  21.01  24.4   17.42  18.56  15.73  17.68  16.13
  13.79  18.25  18.3   15.5   15.17  14.99  11.9   15.29  16.09  16.47
  20.09  21.63  15.26  11.57  17.03  20.8   17.19  12.    23.9   20.04
 110.    14.59  14.    18.45  16.96  12.65  19.33  19.65  22.15  25.
  14.82  10.75  21.73   8.    16.1   20.68  22.7   11.36  13.4   18.49
  14.28  17.88  16.11  20.7   16.82  17.3   20.46  12.35  15.04  18.75
  15.2   18.12  18.06  11.7   20.1   22.74  28.09  17.67  20.88  26.11
  22.1   13.5   24.52  20.25  13.58  10.54  15.7   19.64 140.    13.68
  16.24  26.59  13.7   17.6   19.69  15.41  14.9   17.52  17.05  24.7
  21.9   25.4   19.47  21.66  25.8   10.5   14.4    9.    19.09  23.01
  22.25  27.28  21.64  22.61  15.8   18.09  19.28  18.78  11.74   8.9
  15.85  18.76  16.95  23.59  14.84  19.5   21.    15.96  27.3   18.88
  13.93  14.74  16.4   16.28  20.86  18.07  21.79  16.6   13.9   26.1
  13.92  18.55  14.02  31.59  19.72  14.57  21.8 ]
------------------------------
Unique values in column 'RTO':
[45 15 13 47 14 11 63 40 12  8 79 43 26 44 18 64 51 27 46 30 32 66 21 60
 41 20 53 48 17 24 23 69 16 29 22 37 28 34 54 50 31 19 38 39 25  4 73 36
 42  1  5 61 68 57 67 78 76 59 56 77 75 72 55 62 49 52 33 71  6 74  3  0
  9 65  7  2 58 10 35 70]
------------------------------
Unique values in column 'Fuel Type':
[4 1 3 0 2]
------------------------------
Unique values in column 'Registration Year':
[2015 2018 2014 2020 2017 2021 2019 2022 2016 2011 2009 2013 2010 2008
 2006 2012 2005 2007 2023 2004 2003 2002]
------------------------------
Unique values in column 'modelYear':
[2015 2018 2014 2020 2017 2021 2019 2022 2016 2011 2009 2013 2010 2008
 2006 2012 2005 2007 2023 1995 1998 2004 2003 2001 2002 2000]
------------------------------
Unique values in column 'Insurance Validity':
[4 5 3 6 2 1 0]
------------------------------
Unique values in column 'Gear Box':
[5 6 7 4 8 9 0 1]
------------------------------
Unique values in column 'Transmission':
[1 0]
------------------------------
Unique values in column 'Seats':
[ 5  7  4  6  8 10  9]
------------------------------
Unique values in column 'City':
[0]
------------------------------
Unique values in column 'Engine Displacement':
[ 998 1497 1199 1197 1248 1956 1198 1462 2179 1950 1396 1995 1498 4663
 1086 1991 1968 1998 2982 1461 1797  796 1353 2925 2987 2967  999 1341
 1496 1582 1798 1120 1969 1451  814 1999 1591 1397 1368 1598 3198 1196
 2993 2755 2143 2354 1332 2199 1997 1499 2148 2696 1364 2494 1373 1299
 1061 1493 2497 1495 1590 1896 1330 1781 1390 1194 2953 1399 1595 2496
    0 1984 2694 1298 2362  970 2198 1599  993 2393 1389 1597 2498 2523
 1586  995 2499 2998   72 1589  624 1596  799 3597 2184 1405 5000 1422
 1047 2200 2996 1108 2400 1996 1395]
------------------------------

In [23]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd  # Assuming df_Banglore_1 is a pandas DataFrame

# Assuming df_Banglore_1 is already loaded

# Step 1: Standardize the text
df_Banglore_1['Insurance Validity'] = df_Banglore_1['Insurance Validity'].astype(str).str.strip()

# Step 2: Define the custom order
insurance_order = [
    'Not Available',
    '1',
    '2',
    'Third Party',
    'Third Party insurance',
    'Comprehensive',
    'Zero Dep'
]

# Step 2.1: Inspect unique values in your column
print("Unique values in 'Insurance Validity' before encoding:")
print(df_Banglore_1['Insurance Validity'].unique())

# Step 2.2: Clean or map inconsistent values if necessary
# Example: Mapping numerical strings to the intended categories
mapping = {
    '1.0': '1',
    '2.0': '2',
    '3.0': 'Third Party',
    '4.0': 'Third Party insurance',
    '5.0': 'Comprehensive',
    '6.0': 'Zero Dep',
    '0.0': 'Not Available' # Assuming 0.0 might correspond to 'Not Available'
}
df_Banglore_1['Insurance Validity'] = df_Banglore_1['Insurance Validity'].replace(mapping)

# Re-inspect unique values after potential mapping
print("\nUnique values in 'Insurance Validity' after potential mapping:")
print(df_Banglore_1['Insurance Validity'].unique())

# Step 3: Apply OrdinalEncoder with that order
oe = OrdinalEncoder(categories=[insurance_order])
df_Banglore_1[['Insurance Validity']] = oe.fit_transform(df_Banglore_1[['Insurance Validity']])

# Step 4: Show result
print("\nEncoded 'Insurance Validity' column:")
print(df_Banglore_1[['Insurance Validity']].head())

Unique values in 'Insurance Validity' before encoding:
['4.0' '5.0' '3.0' '6.0' '2.0' '1.0' '0.0']

Unique values in 'Insurance Validity' after potential mapping:
['Third Party insurance' 'Comprehensive' 'Third Party' 'Zero Dep' '2' '1'
 'Not Available']

Encoded 'Insurance Validity' column:
   Insurance Validity
0                 4.0
1                 5.0
2                 5.0
3                 5.0
4                 4.0

In [18]:
df_Banglore_1.head()

,price,bt,Kms Driven,owner,Year of Manufacture,Mileage,RTO,Fuel Type,Registration Year,modelYear,Insurance Validity,Gear Box,Transmission,Seats,City,Engine Displacement
0,400000,Hatchback,120000,3,2015,23.10,KA51,Petrol,2015,2015,4.0,5,Manual,5,bangalore,998
1,811000,SUV,32706,2,2018,17.00,KA05,Petrol,2018,2018,5.0,5,Manual,5,bangalore,1497
2,585000,Hatchback,11949,1,2018,23.84,KA03,Petrol,2018,2018,5.0,5,Manual,5,bangalore,1199
3,462000,Sedan,17794,1,2014,19.10,KA53,Petrol,2014,2014,5.0,5,Manual,5,bangalore,1197
4,790000,SUV,60000,1,2015,23.65,KA04,Diesel,2015,2015,4.0,5,Manual,5,bangalore,1248